"""drop issue status_note

Revision ID: 0a235cf5f419
Revises: 2e1c2a9b7fbb
Create Date: 2026-08-04 12:57:01.017577
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0a235cf5f419"
down_revision: str | None = "2e1c2a9b7fbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_column("status_note")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status_note", sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
