"""add issue due date

Revision ID: 2b4d65e2e059
Revises: 0a235cf5f419
Create Date: 2026-08-04 19:48:11.095911
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2b4d65e2e059"
down_revision: str | None = "0a235cf5f419"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("due_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_column("due_date")

    # ### end Alembic commands ###
