"""initial schema

Revision ID: e8f29f68d811
Revises:
Create Date: 2026-08-03 18:01:08.220485
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e8f29f68d811"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(
            "projects_slug_live", ["slug"], unique=True, sqlite_where=sa.text("deleted_at IS NULL")
        )

    op.create_table(
        "issues",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index(
            "issues_by_project",
            ["project_id", "status"],
            unique=False,
            sqlite_where=sa.text("deleted_at IS NULL"),
        )
        batch_op.create_index(batch_op.f("ix_issues_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issues_project_id"))
        batch_op.drop_index(batch_op.f("ix_issues_deleted_at"))
        batch_op.drop_index("issues_by_project", sqlite_where=sa.text("deleted_at IS NULL"))

    op.drop_table("issues")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("projects_slug_live", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_index(batch_op.f("ix_projects_deleted_at"))

    op.drop_table("projects")
    # ### end Alembic commands ###
