"""add milestones and issue milestone link

Revision ID: 46393fcfd908
Revises: 3a8cb1a03476
Create Date: 2026-08-04 21:33:48.785506
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "46393fcfd908"
down_revision: str | None = "3a8cb1a03476"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("epic_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["epic_id"], ["epics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_milestones_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_milestones_epic_id"), ["epic_id"], unique=False)
        batch_op.create_index(
            "milestones_by_epic",
            ["epic_id"],
            unique=False,
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("milestone_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_issues_milestone_id"), ["milestone_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_issues_milestone_id_milestones",
            "milestones",
            ["milestone_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_constraint("fk_issues_milestone_id_milestones", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_issues_milestone_id"))
        batch_op.drop_column("milestone_id")

    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.drop_index("milestones_by_epic", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_index(batch_op.f("ix_milestones_epic_id"))
        batch_op.drop_index(batch_op.f("ix_milestones_deleted_at"))

    op.drop_table("milestones")
    # ### end Alembic commands ###
