"""add per-project sequence counters

Revision ID: 762216d69769
Revises: 675604eef2ca
Create Date: 2026-08-04 22:17:16.428996
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "762216d69769"
down_revision: str | None = "675604eef2ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequences",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "type", name="uq_sequences_project_type"),
    )
    with op.batch_alter_table("sequences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sequences_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sequences_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sequences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sequences_project_id"))
        batch_op.drop_index(batch_op.f("ix_sequences_deleted_at"))

    op.drop_table("sequences")
    # ### end Alembic commands ###
