"""add project path

Revision ID: 2e1c2a9b7fbb
Revises: e8f29f68d811
Create Date: 2026-08-03 23:18:38.455655
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e1c2a9b7fbb"
down_revision: str | None = "e8f29f68d811"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("path", sa.Text(), nullable=True))
        batch_op.create_index(
            "projects_path_live", ["path"], unique=True, sqlite_where=sa.text("deleted_at IS NULL")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("projects_path_live", sqlite_where=sa.text("deleted_at IS NULL"))
        batch_op.drop_column("path")

    # ### end Alembic commands ###
