"""add issue dependencies

Revision ID: 63b5325a9ed0
Revises: cf62ed046fd8
Create Date: 2026-08-07 09:21:35.725144
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "63b5325a9ed0"
down_revision: str | None = "cf62ed046fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_dependencies",
        sa.Column("blocker_id", sa.Integer(), nullable=False),
        sa.Column("blocked_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["blocked_id"], ["issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["blocker_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("blocker_id", "blocked_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issue_dependencies")
    # ### end Alembic commands ###
