// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Plabrum/tt/backend/internal/ent/issue"
	"github.com/Plabrum/tt/backend/internal/ent/milestone"
	"github.com/Plabrum/tt/backend/internal/ent/project"
)

// MilestoneCreate is the builder for creating a Milestone entity.
type MilestoneCreate struct {
	config
	mutation *MilestoneMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MilestoneCreate) SetCreatedAt(v time.Time) *MilestoneCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableCreatedAt(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MilestoneCreate) SetUpdatedAt(v time.Time) *MilestoneCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableUpdatedAt(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *MilestoneCreate) SetName(v string) *MilestoneCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDue sets the "due" field.
func (_c *MilestoneCreate) SetDue(v time.Time) *MilestoneCreate {
	_c.mutation.SetDue(v)
	return _c
}

// SetNillableDue sets the "due" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableDue(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetDue(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *MilestoneCreate) SetDescription(v string) *MilestoneCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableDescription(v *string) *MilestoneCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *MilestoneCreate) SetProjectID(id int) *MilestoneCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *MilestoneCreate) SetProject(v *Project) *MilestoneCreate {
	return _c.SetProjectID(v.ID)
}

// AddIssueIDs adds the "issues" edge to the Issue entity by IDs.
func (_c *MilestoneCreate) AddIssueIDs(ids ...int) *MilestoneCreate {
	_c.mutation.AddIssueIDs(ids...)
	return _c
}

// AddIssues adds the "issues" edges to the Issue entity.
func (_c *MilestoneCreate) AddIssues(v ...*Issue) *MilestoneCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIssueIDs(ids...)
}

// Mutation returns the MilestoneMutation object of the builder.
func (_c *MilestoneCreate) Mutation() *MilestoneMutation {
	return _c.mutation
}

// Save creates the Milestone in the database.
func (_c *MilestoneCreate) Save(ctx context.Context) (*Milestone, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MilestoneCreate) SaveX(ctx context.Context) *Milestone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilestoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilestoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MilestoneCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := milestone.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := milestone.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := milestone.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MilestoneCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Milestone.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Milestone.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Milestone.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := milestone.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Milestone.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Milestone.description"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Milestone.project"`)}
	}
	return nil
}

func (_c *MilestoneCreate) sqlSave(ctx context.Context) (*Milestone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MilestoneCreate) createSpec() (*Milestone, *sqlgraph.CreateSpec) {
	var (
		_node = &Milestone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(milestone.Table, sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(milestone.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(milestone.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(milestone.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Due(); ok {
		_spec.SetField(milestone.FieldDue, field.TypeTime, value)
		_node.Due = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(milestone.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   milestone.ProjectTable,
			Columns: []string{milestone.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_milestones = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   milestone.IssuesTable,
			Columns: []string{milestone.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Milestone.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MilestoneUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MilestoneCreate) OnConflict(opts ...sql.ConflictOption) *MilestoneUpsertOne {
	_c.conflict = opts
	return &MilestoneUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Milestone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MilestoneCreate) OnConflictColumns(columns ...string) *MilestoneUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MilestoneUpsertOne{
		create: _c,
	}
}

type (
	// MilestoneUpsertOne is the builder for "upsert"-ing
	//  one Milestone node.
	MilestoneUpsertOne struct {
		create *MilestoneCreate
	}

	// MilestoneUpsert is the "OnConflict" setter.
	MilestoneUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MilestoneUpsert) SetUpdatedAt(v time.Time) *MilestoneUpsert {
	u.Set(milestone.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MilestoneUpsert) UpdateUpdatedAt() *MilestoneUpsert {
	u.SetExcluded(milestone.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *MilestoneUpsert) SetName(v string) *MilestoneUpsert {
	u.Set(milestone.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MilestoneUpsert) UpdateName() *MilestoneUpsert {
	u.SetExcluded(milestone.FieldName)
	return u
}

// SetDue sets the "due" field.
func (u *MilestoneUpsert) SetDue(v time.Time) *MilestoneUpsert {
	u.Set(milestone.FieldDue, v)
	return u
}

// UpdateDue sets the "due" field to the value that was provided on create.
func (u *MilestoneUpsert) UpdateDue() *MilestoneUpsert {
	u.SetExcluded(milestone.FieldDue)
	return u
}

// ClearDue clears the value of the "due" field.
func (u *MilestoneUpsert) ClearDue() *MilestoneUpsert {
	u.SetNull(milestone.FieldDue)
	return u
}

// SetDescription sets the "description" field.
func (u *MilestoneUpsert) SetDescription(v string) *MilestoneUpsert {
	u.Set(milestone.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MilestoneUpsert) UpdateDescription() *MilestoneUpsert {
	u.SetExcluded(milestone.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Milestone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MilestoneUpsertOne) UpdateNewValues() *MilestoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(milestone.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Milestone.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MilestoneUpsertOne) Ignore() *MilestoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MilestoneUpsertOne) DoNothing() *MilestoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MilestoneCreate.OnConflict
// documentation for more info.
func (u *MilestoneUpsertOne) Update(set func(*MilestoneUpsert)) *MilestoneUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MilestoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MilestoneUpsertOne) SetUpdatedAt(v time.Time) *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MilestoneUpsertOne) UpdateUpdatedAt() *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *MilestoneUpsertOne) SetName(v string) *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MilestoneUpsertOne) UpdateName() *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateName()
	})
}

// SetDue sets the "due" field.
func (u *MilestoneUpsertOne) SetDue(v time.Time) *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetDue(v)
	})
}

// UpdateDue sets the "due" field to the value that was provided on create.
func (u *MilestoneUpsertOne) UpdateDue() *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateDue()
	})
}

// ClearDue clears the value of the "due" field.
func (u *MilestoneUpsertOne) ClearDue() *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.ClearDue()
	})
}

// SetDescription sets the "description" field.
func (u *MilestoneUpsertOne) SetDescription(v string) *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MilestoneUpsertOne) UpdateDescription() *MilestoneUpsertOne {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateDescription()
	})
}

// Exec executes the query.
func (u *MilestoneUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MilestoneCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MilestoneUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MilestoneUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MilestoneUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MilestoneCreateBulk is the builder for creating many Milestone entities in bulk.
type MilestoneCreateBulk struct {
	config
	err      error
	builders []*MilestoneCreate
	conflict []sql.ConflictOption
}

// Save creates the Milestone entities in the database.
func (_c *MilestoneCreateBulk) Save(ctx context.Context) ([]*Milestone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Milestone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MilestoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MilestoneCreateBulk) SaveX(ctx context.Context) []*Milestone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilestoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilestoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Milestone.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MilestoneUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MilestoneCreateBulk) OnConflict(opts ...sql.ConflictOption) *MilestoneUpsertBulk {
	_c.conflict = opts
	return &MilestoneUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Milestone.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MilestoneCreateBulk) OnConflictColumns(columns ...string) *MilestoneUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MilestoneUpsertBulk{
		create: _c,
	}
}

// MilestoneUpsertBulk is the builder for "upsert"-ing
// a bulk of Milestone nodes.
type MilestoneUpsertBulk struct {
	create *MilestoneCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Milestone.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MilestoneUpsertBulk) UpdateNewValues() *MilestoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(milestone.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Milestone.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MilestoneUpsertBulk) Ignore() *MilestoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MilestoneUpsertBulk) DoNothing() *MilestoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MilestoneCreateBulk.OnConflict
// documentation for more info.
func (u *MilestoneUpsertBulk) Update(set func(*MilestoneUpsert)) *MilestoneUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MilestoneUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MilestoneUpsertBulk) SetUpdatedAt(v time.Time) *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MilestoneUpsertBulk) UpdateUpdatedAt() *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *MilestoneUpsertBulk) SetName(v string) *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MilestoneUpsertBulk) UpdateName() *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateName()
	})
}

// SetDue sets the "due" field.
func (u *MilestoneUpsertBulk) SetDue(v time.Time) *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetDue(v)
	})
}

// UpdateDue sets the "due" field to the value that was provided on create.
func (u *MilestoneUpsertBulk) UpdateDue() *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateDue()
	})
}

// ClearDue clears the value of the "due" field.
func (u *MilestoneUpsertBulk) ClearDue() *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.ClearDue()
	})
}

// SetDescription sets the "description" field.
func (u *MilestoneUpsertBulk) SetDescription(v string) *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MilestoneUpsertBulk) UpdateDescription() *MilestoneUpsertBulk {
	return u.Update(func(s *MilestoneUpsert) {
		s.UpdateDescription()
	})
}

// Exec executes the query.
func (u *MilestoneUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MilestoneCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MilestoneCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MilestoneUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
