// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Plabrum/tt/backend/internal/ent/issue"
	"github.com/Plabrum/tt/backend/internal/ent/predicate"
	"github.com/Plabrum/tt/backend/internal/ent/ref"
)

// RefUpdate is the builder for updating Ref entities.
type RefUpdate struct {
	config
	hooks    []Hook
	mutation *RefMutation
}

// Where appends a list predicates to the RefUpdate builder.
func (_u *RefUpdate) Where(ps ...predicate.Ref) *RefUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefUpdate) SetUpdatedAt(v time.Time) *RefUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlockedID sets the "blocked_id" field.
func (_u *RefUpdate) SetBlockedID(v int) *RefUpdate {
	_u.mutation.SetBlockedID(v)
	return _u
}

// SetNillableBlockedID sets the "blocked_id" field if the given value is not nil.
func (_u *RefUpdate) SetNillableBlockedID(v *int) *RefUpdate {
	if v != nil {
		_u.SetBlockedID(*v)
	}
	return _u
}

// SetBlockerID sets the "blocker_id" field.
func (_u *RefUpdate) SetBlockerID(v int) *RefUpdate {
	_u.mutation.SetBlockerID(v)
	return _u
}

// SetNillableBlockerID sets the "blocker_id" field if the given value is not nil.
func (_u *RefUpdate) SetNillableBlockerID(v *int) *RefUpdate {
	if v != nil {
		_u.SetBlockerID(*v)
	}
	return _u
}

// SetBlocked sets the "blocked" edge to the Issue entity.
func (_u *RefUpdate) SetBlocked(v *Issue) *RefUpdate {
	return _u.SetBlockedID(v.ID)
}

// SetBlocker sets the "blocker" edge to the Issue entity.
func (_u *RefUpdate) SetBlocker(v *Issue) *RefUpdate {
	return _u.SetBlockerID(v.ID)
}

// Mutation returns the RefMutation object of the builder.
func (_u *RefUpdate) Mutation() *RefMutation {
	return _u.mutation
}

// ClearBlocked clears the "blocked" edge to the Issue entity.
func (_u *RefUpdate) ClearBlocked() *RefUpdate {
	_u.mutation.ClearBlocked()
	return _u
}

// ClearBlocker clears the "blocker" edge to the Issue entity.
func (_u *RefUpdate) ClearBlocker() *RefUpdate {
	_u.mutation.ClearBlocker()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RefUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RefUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ref.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ref.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ref.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefUpdate) check() error {
	if _u.mutation.BlockedCleared() && len(_u.mutation.BlockedIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ref.blocked"`)
	}
	if _u.mutation.BlockerCleared() && len(_u.mutation.BlockerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ref.blocker"`)
	}
	return nil
}

func (_u *RefUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ref.Table, ref.Columns, sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ref.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BlockedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockedTable,
			Columns: []string{ref.BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockedTable,
			Columns: []string{ref.BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockerTable,
			Columns: []string{ref.BlockerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockerTable,
			Columns: []string{ref.BlockerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RefUpdateOne is the builder for updating a single Ref entity.
type RefUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefUpdateOne) SetUpdatedAt(v time.Time) *RefUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlockedID sets the "blocked_id" field.
func (_u *RefUpdateOne) SetBlockedID(v int) *RefUpdateOne {
	_u.mutation.SetBlockedID(v)
	return _u
}

// SetNillableBlockedID sets the "blocked_id" field if the given value is not nil.
func (_u *RefUpdateOne) SetNillableBlockedID(v *int) *RefUpdateOne {
	if v != nil {
		_u.SetBlockedID(*v)
	}
	return _u
}

// SetBlockerID sets the "blocker_id" field.
func (_u *RefUpdateOne) SetBlockerID(v int) *RefUpdateOne {
	_u.mutation.SetBlockerID(v)
	return _u
}

// SetNillableBlockerID sets the "blocker_id" field if the given value is not nil.
func (_u *RefUpdateOne) SetNillableBlockerID(v *int) *RefUpdateOne {
	if v != nil {
		_u.SetBlockerID(*v)
	}
	return _u
}

// SetBlocked sets the "blocked" edge to the Issue entity.
func (_u *RefUpdateOne) SetBlocked(v *Issue) *RefUpdateOne {
	return _u.SetBlockedID(v.ID)
}

// SetBlocker sets the "blocker" edge to the Issue entity.
func (_u *RefUpdateOne) SetBlocker(v *Issue) *RefUpdateOne {
	return _u.SetBlockerID(v.ID)
}

// Mutation returns the RefMutation object of the builder.
func (_u *RefUpdateOne) Mutation() *RefMutation {
	return _u.mutation
}

// ClearBlocked clears the "blocked" edge to the Issue entity.
func (_u *RefUpdateOne) ClearBlocked() *RefUpdateOne {
	_u.mutation.ClearBlocked()
	return _u
}

// ClearBlocker clears the "blocker" edge to the Issue entity.
func (_u *RefUpdateOne) ClearBlocker() *RefUpdateOne {
	_u.mutation.ClearBlocker()
	return _u
}

// Where appends a list predicates to the RefUpdate builder.
func (_u *RefUpdateOne) Where(ps ...predicate.Ref) *RefUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RefUpdateOne) Select(field string, fields ...string) *RefUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ref entity.
func (_u *RefUpdateOne) Save(ctx context.Context) (*Ref, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefUpdateOne) SaveX(ctx context.Context) *Ref {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RefUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ref.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ref.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ref.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefUpdateOne) check() error {
	if _u.mutation.BlockedCleared() && len(_u.mutation.BlockedIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ref.blocked"`)
	}
	if _u.mutation.BlockerCleared() && len(_u.mutation.BlockerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ref.blocker"`)
	}
	return nil
}

func (_u *RefUpdateOne) sqlSave(ctx context.Context) (_node *Ref, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ref.Table, ref.Columns, sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ref.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ref.FieldID)
		for _, f := range fields {
			if !ref.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ref.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BlockedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockedTable,
			Columns: []string{ref.BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockedTable,
			Columns: []string{ref.BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockerTable,
			Columns: []string{ref.BlockerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockerTable,
			Columns: []string{ref.BlockerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ref{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
