"""The domain with a shell or an agent on the end of it.

Same handful of calls the TUI makes, through the same ``api``: what an object
offers, the fields each action wants, and the write. Nothing here names an action
key — an action gets a subcommand because ``action_schemas`` lists it, and that
subcommand's options are the fields its payload derived. Adding a fifth issue
action changes no line of this file.

Two ways in, over the same ``api``. ``action KEY JSON`` is the raw path: one
command carrying any action's payload as a blob, which is what an agent holding
the output of ``show`` already has. The per-action subcommands are the same
dispatch with the blob spelled out as options, for a person at a prompt. Both end
at ``api.trigger``, so neither can reach an action the other cannot.

Typer draws the tree, but the per-action subcommands are built from
``action_schemas`` at run time: a command function is synthesised for each key,
its options the ``Field``\\ s the payload derived. A hand-written command per
action would name every key a second time and reintroduce the drift this design
exists to remove. Typer 0.27 vendors a pared-down Click that does not expose the
``Command``/``Option`` object API, so the subcommands are generated by giving each
command function a signature built at run time rather than by constructing Click
objects directly.
"""

import enum
import inspect
import json
import os
import subprocess
from collections.abc import Callable
from importlib.metadata import version as package_version
from pathlib import Path
from typing import Annotated, Any, cast

import typer
from sqlalchemy import Engine

from tt import schema
from tt.domains.comment import api as comment_api
from tt.domains.epic import api as epic_api
from tt.domains.epic.schemas import EpicListItem
from tt.domains.issue import api as issue_api
from tt.domains.issue.enums import Direction, SortField
from tt.domains.issue.queries import IssueFilter, IssueSort
from tt.domains.issue.schemas import IssueListItem
from tt.domains.milestone import api as milestone_api
from tt.domains.milestone.schemas import MilestoneListItem
from tt.domains.project import api as project_api
from tt.domains.project.schemas import ProjectListItem
from tt.domains.tag import api as tag_api
from tt.domains.tag.schemas import TagListItem
from tt.platform import actions
from tt.platform.actions import REFUSALS, Enum, Field, Invalid, Offer, Refused, Runnable
from tt.platform.refs import parse_ref

# A refusal is the object's answer, not a usage error, so it is neither Click's 2
# nor a success. 123 is what the Rust and OCaml spikes both return for the same
# thing — distinct codes for the two refusals are a real tracker's problem and not
# this spike's.
REFUSED = 123

# The help of the two arguments the raw ``action`` path shares, factored out only
# so the command declarations stay one line each.
_KEY_HELP = "The action to run."
_JSON_HELP = "The action's arguments, as a JSON object."

# What a generated command hands its address and payload to.
type Writer = Callable[[Engine, Any, str, dict[str, Any]], str]


# --- rendering ------------------------------------------------------------


def _project_line(p: ProjectListItem) -> str:
    counts = (
        f"{p.backlog} backlog, {p.planning} planning, {p.todo} todo, {p.doing} doing, {p.done} done"
    )
    return f"{p.slug:<12} {p.title:<24} {p.status:<8} {counts}"


def _issue_line(i: IssueListItem) -> str:
    return f"{i.ref:<10} {i.status:<8} {i.priority:<6} {i.title}"


def _epic_line(e: EpicListItem) -> str:
    total = e.backlog + e.planning + e.todo + e.doing + e.done
    progress = f"{e.done}/{total}"
    due = e.due_date.isoformat() if e.due_date is not None else "—"
    return f"{e.ref:<10} {e.status:<8} {due:<12} {progress:<8} {e.title}"


def _milestone_line(m: MilestoneListItem) -> str:
    total = m.backlog + m.planning + m.todo + m.doing + m.done
    progress = f"{m.done}/{total}"
    due = m.due_date.isoformat() if m.due_date is not None else "—"
    return f"{m.ref:<10} epic {m.epic:<10} {due:<12} {progress:<8} {m.title}"


def _tag_line(t: TagListItem) -> str:
    return f"{t.id:<4} {t.name}"


def _field_json(field: Field) -> dict[str, Any]:
    """One argument, as the JSON an agent reads before it fills anything in."""
    base: dict[str, Any] = {
        "name": field.name,
        "required": field.required,
        "description": field.description,
    }
    match field.kind:
        case actions.Text():
            return {**base, "type": "text"}
        case actions.OptionalText():
            return {**base, "type": "text", "optional": True}
        case actions.Date():
            return {**base, "type": "date"}
        case actions.Reference():
            return {**base, "type": "ref"}
        case Enum(values=values):
            return {**base, "type": "enum", "values": values}


def _offer_json(offer: Offer) -> dict[str, Any]:
    """One offered action, as the JSON an agent reads before it picks anything."""
    fields: dict[str, Any] = {"key": offer.key, "label": offer.label}
    match offer.state:
        case Runnable():
            fields["state"] = "runnable"
        case Refused(reason):
            fields["state"] = "refused"
            fields["reason"] = reason
    fields["arguments"] = [_field_json(field) for field in offer.fields]
    return fields


def _pretty(value: Any) -> str:
    return json.dumps(value, indent=2)


# --- the writes -----------------------------------------------------------
#
# The ``api`` opens the transaction, so one call is one write with no ``with``
# here: the hooks are checked against the row as it is now rather than as some
# earlier detail view reported it, and a refusal after rows are written rolls the
# whole call back. A project write carries an optional slug — an object action
# passes one, the top-level ``createProject`` passes ``None``.


def _project_write(engine: Engine, slug: Any, key: str, payload: dict[str, Any]) -> str:
    return project_api.project_action(engine, key, payload, slug).message


def _issue_write(engine: Engine, ref: Any, key: str, payload: dict[str, Any]) -> str:
    return issue_api.issue_action(engine, key, payload, ref).message


def _epic_write(engine: Engine, ref: Any, key: str, payload: dict[str, Any]) -> str:
    return epic_api.epic_action(engine, key, payload, ref).message


def _milestone_write(engine: Engine, ref: Any, key: str, payload: dict[str, Any]) -> str:
    return milestone_api.milestone_action(engine, key, payload, ref).message


def _tag_write(engine: Engine, tag_id: Any, key: str, payload: dict[str, Any]) -> str:
    return tag_api.tag_action(engine, key, payload, tag_id).message


def _comment_write(engine: Engine, comment_id: Any, key: str, payload: dict[str, Any]) -> str:
    return comment_api.comment_action(engine, key, payload, comment_id).message


def _project_init(
    engine: Engine, slug: str, title: str | None, body: str | None, path: str | None
) -> str:
    """``createProject`` with the directory it binds filled in.

    ``init`` names the ``createProject`` key rather than being generated like the
    object actions: a top-level create has no address to hang a subcommand on, and
    ``init``'s point is a default no generated command could supply. The project
    binds to the current directory unless ``--path`` overrides it, so bare ``tt``
    resolves and opens it there afterwards.
    """
    directory = os.path.abspath(os.path.expanduser(path)) if path is not None else os.getcwd()
    payload: dict[str, Any] = {"slug": slug, "path": directory}
    if title is not None:
        payload["title"] = title
    if body is not None:
        payload["body"] = body
    return _project_write(engine, None, "createProject", payload)


# --- the reads ------------------------------------------------------------


def _project_ls(engine: Engine, as_json: bool) -> str:
    items = project_api.project_list(engine)
    if as_json:
        return _pretty([item.model_dump(mode="json") for item in items])
    return "\n".join(_project_line(p) for p in items)


def _parse_sort(raw: str | None) -> IssueSort:
    """A ``--sort`` value, ``<field>[:<direction>]``, as the sort it names. A bad
    field or direction is a usage error listing what is allowed, not a refusal — it
    is the invocation that is wrong, not the data."""
    if raw is None:
        return IssueSort()
    field_text, sep, direction_text = raw.partition(":")
    try:
        field = SortField(field_text)
    except ValueError as e:
        allowed = ", ".join(f.value for f in SortField)
        raise typer.BadParameter(
            f"unknown sort field {field_text!r}; choose one of {allowed}"
        ) from e
    if not sep:
        return IssueSort(field=field)
    try:
        direction = Direction(direction_text)
    except ValueError as e:
        raise typer.BadParameter(
            f"unknown sort direction {direction_text!r}; use asc or desc"
        ) from e
    return IssueSort(field=field, direction=direction)


def _epic_id(engine: Engine, project_slug: str, ref: str) -> int:
    """The id of the epic a ref names within the project, or a refusal. The ref
    carries its own project's slug, so one from another project is no epic here."""
    epic = epic_api.epic_get(engine, ref)
    if epic is None or epic.project != project_slug:
        raise Invalid(f"no epic {ref} in project {project_slug!r}")
    return epic.id


def _milestone_id(engine: Engine, project_slug: str, ref: str) -> int:
    """The id of the milestone a ref names within the project, or a refusal. A
    milestone's ref is ``<project slug>-<number>`` like an epic's, so its slug is
    what places it in the project."""
    milestone = milestone_api.milestone_get(engine, ref)
    parsed = parse_ref(ref)
    if milestone is None or parsed is None or parsed[0] != project_slug:
        raise Invalid(f"no milestone {ref} in project {project_slug!r}")
    return milestone.id


def _issue_ls(
    engine: Engine,
    project_slug: str | None,
    tag: str | None,
    epic: str | None,
    milestone: str | None,
    sort: IssueSort,
    as_json: bool,
) -> str:
    if project_slug is None:
        # An epic or milestone ref is project-scoped, so filtering by one only makes
        # sense once a project is named; a bare ref would range over every project.
        if epic is not None or milestone is not None:
            raise typer.BadParameter("--epic and --milestone need --project")
        slugs = [p.slug for p in project_api.project_list(engine)]
        filter = IssueFilter(tag=tag)
    else:
        if project_api.project_get(engine, project_slug) is None:
            raise Invalid(f"no project {project_slug!r}")
        slugs = [project_slug]
        filter = IssueFilter(
            tag=tag,
            epic_id=_epic_id(engine, project_slug, epic) if epic is not None else None,
            milestone_id=_milestone_id(engine, project_slug, milestone)
            if milestone is not None
            else None,
        )
    items = [issue for slug in slugs for issue in issue_api.issue_list(engine, slug, filter, sort)]
    if as_json:
        return _pretty([item.model_dump(mode="json") for item in items])
    return "\n".join(_issue_line(i) for i in items)


def _epic_ls(engine: Engine, project_slug: str | None, as_json: bool) -> str:
    if project_slug is not None:
        if project_api.project_get(engine, project_slug) is None:
            raise Invalid(f"no project {project_slug!r}")
        slugs = [project_slug]
    else:
        slugs = [p.slug for p in project_api.project_list(engine)]
    items = [epic for slug in slugs for epic in epic_api.epic_list(engine, slug)]
    if as_json:
        return _pretty([item.model_dump(mode="json") for item in items])
    return "\n".join(_epic_line(e) for e in items)


def _project_show(engine: Engine, slug: str) -> str:
    detail, offers = project_api.project_detail(engine, slug)
    actions = [_offer_json(offer) for offer in offers]
    return _pretty({"project": detail.model_dump(mode="json"), "actions": actions})


def _epic_show(engine: Engine, ref: str) -> str:
    detail, offers = epic_api.epic_detail(engine, ref)
    actions = [_offer_json(offer) for offer in offers]
    return _pretty({"epic": detail.model_dump(mode="json"), "actions": actions})


def _epic_ids(engine: Engine) -> list[int]:
    """Every live epic id across every live project — what a milestone list with no
    epic named ranges over. Ids, not refs: they feed ``milestone_list``, which reads
    by the epic's own id rather than resolving a ref per epic."""
    return [
        epic.id
        for project in project_api.project_list(engine)
        for epic in epic_api.epic_list(engine, project.slug)
    ]


def _milestone_ls(engine: Engine, epic_ref: str | None, as_json: bool) -> str:
    if epic_ref is not None:
        epic = epic_api.epic_get(engine, epic_ref)
        if epic is None:
            raise Invalid(f"no epic {epic_ref}")
        epic_ids = [epic.id]
    else:
        epic_ids = _epic_ids(engine)
    items = [m for eid in epic_ids for m in milestone_api.milestone_list(engine, eid)]
    if as_json:
        return _pretty([item.model_dump(mode="json") for item in items])
    return "\n".join(_milestone_line(m) for m in items)


def _milestone_show(engine: Engine, ref: str) -> str:
    detail, offers = milestone_api.milestone_detail(engine, ref)
    actions = [_offer_json(offer) for offer in offers]
    return _pretty({"milestone": detail.model_dump(mode="json"), "actions": actions})


def _tag_ls(engine: Engine, as_json: bool) -> str:
    items = tag_api.tag_list(engine)
    if as_json:
        return _pretty([item.model_dump(mode="json") for item in items])
    return "\n".join(_tag_line(t) for t in items)


def _issue_show(engine: Engine, ref: str) -> str:
    detail, offers = issue_api.issue_detail(engine, ref)
    actions = [_offer_json(offer) for offer in offers]
    return _pretty({"issue": detail.model_dump(mode="json"), "actions": actions})


def _comment_show(engine: Engine, comment_id: int) -> str:
    detail, offers = comment_api.comment_detail(engine, comment_id)
    actions = [_offer_json(offer) for offer in offers]
    return _pretty({"comment": detail.model_dump(mode="json"), "actions": actions})


# --- the arguments a typed-in command carries -----------------------------


def _blob(raw: str) -> dict[str, Any]:
    try:
        value: Any = json.loads(raw)
    except json.JSONDecodeError as e:
        raise Invalid(str(e)) from e
    if not isinstance(value, dict):
        raise Invalid("the payload must be a JSON object")
    return value


def _as_str(value: Any) -> str:
    """The string a field's option value carries into ``action.payload``. An enum
    option arrives as its member, whose ``.value`` is the wire string the field
    advertised; everything else is already the text that was typed."""
    if isinstance(value, enum.Enum):
        return str(value.value)
    return str(value)


def _payload_of(fields: list[Field], values: dict[str, Any]) -> dict[str, Any]:
    """What the typed-in options make.

    An option that was not passed is dropped rather than sent, which is what lets
    ``--note`` absent and ``--note ""`` mean different things: the first omits the
    field, the second sends the ``null`` ``action.payload`` encodes a blank
    optional as. Only an optional field can be absent — a required one is the
    parser's to demand — so a ``None`` against an optional field is the "not
    passed" signal.
    """
    given = [
        (field, _as_str(values[field.name]))
        for field in fields
        if field.required or values.get(field.name) is not None
    ]
    return actions.payload(given)


# --- the generated subcommands --------------------------------------------


def _enum_type(name: str, values: list[str]) -> type[enum.Enum]:
    """A closed Click choice, as the ``enum.Enum`` Typer turns into one. Its
    members' values are the wire strings, which is what Typer shows and accepts."""
    # The functional ``Enum`` call is typed as returning a member, not the class it
    # actually builds, so the cast restores what Typer needs as an annotation.
    return cast("type[enum.Enum]", enum.Enum(name, {value: value for value in values}, type=str))


def _option_annotation(field: Field) -> Any:
    """One ``--<field>`` option, its type the field's kind and its help the field's
    description. A ``Kind.Enum`` becomes a closed choice, so a bad value is a usage
    error listing the alternatives rather than a decode failure quoting a type.

    The requirement is not restated here beyond ``required=`` — what a title has to
    *contain* is the action's, which is why a blank one gets past this and is
    refused by ``execute``."""
    kind = field.kind
    base: Any = _enum_type(field.name, kind.values) if isinstance(kind, Enum) else str
    option = typer.Option(f"--{field.name}", help=field.description or "")
    if field.required:
        return Annotated[base, option]
    return Annotated[base | None, option]


def _generated(
    key: str,
    fields: list[Field],
    address_name: str,
    address_type: type,
    address_help: str,
    write: Writer,
) -> Callable[..., None]:
    """One command function per action, whether or not it applies now.

    Availability belongs to an object and a command tree does not have one yet — the
    subcommand is parsed before the row has been read. So ``delete`` is a command on
    an active project too, and the refusal comes back from the dispatch against the
    live object rather than from the parser.
    """
    address_annotation = Annotated[address_type, typer.Argument(help=address_help)]

    def impl(**kwargs: Any) -> None:
        def outcome() -> str:
            payload = _payload_of(fields, kwargs)
            engine = _engine(kwargs["ctx"])
            return write(engine, kwargs[address_name], key, payload)

        _report(outcome)

    parameters = [
        inspect.Parameter("ctx", inspect.Parameter.POSITIONAL_OR_KEYWORD, annotation=typer.Context),
        inspect.Parameter(
            address_name,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
            annotation=address_annotation,
        ),
    ]
    annotations: dict[str, Any] = {"ctx": typer.Context, address_name: address_annotation}
    for field in fields:
        annotation = _option_annotation(field)
        parameters.append(
            inspect.Parameter(
                field.name,
                inspect.Parameter.KEYWORD_ONLY,
                annotation=annotation,
                default=inspect.Parameter.empty if field.required else None,
            )
        )
        annotations[field.name] = annotation

    impl.__signature__ = inspect.Signature(parameters)  # pyright: ignore[reportFunctionMemberAccess]
    impl.__annotations__ = annotations
    impl.__name__ = key
    return impl


def _register_generated(
    sub_app: typer.Typer,
    keys: list[tuple[str, list[Field]]],
    address_name: str,
    address_type: type,
    address_help: str,
    write: Writer,
) -> None:
    for key, fields in keys:
        command = _generated(key, fields, address_name, address_type, address_help, write)
        sub_app.command(key)(command)


# --- the runtime edge -----------------------------------------------------


def _engine(ctx: typer.Context) -> Engine:
    engine = ctx.obj
    assert isinstance(engine, Engine)
    return engine


def _report(outcome: Callable[[], str]) -> None:
    """Run one command against the open database. On success print what it made; on
    any refusal print it to stderr and exit 123."""
    try:
        message = outcome()
    except REFUSALS as error:
        typer.echo(str(error), err=True)
        raise typer.Exit(code=REFUSED) from error
    typer.echo(message)


# --- version --------------------------------------------------------------

# The checkout tt is imported from: ``.../tt/frontend/cli.py`` up to the repo
# root. tt is installed editable, so which tree is on ``PATH`` — not the frozen
# package version — is what tells one build from another, and this is how
# ``--version`` reports it.
_SOURCE_ROOT = Path(__file__).resolve().parents[2]


def _git(source: Path, *args: str) -> str | None:
    """The output of a ``git`` command run in ``source``, or ``None`` when git is
    absent or ``source`` is not a checkout — a wheel install has no repository."""
    try:
        done = subprocess.run(
            ["git", "-C", str(source), *args],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return done.stdout.strip()


def _source_revision(source: Path) -> str | None:
    """``source``'s short revision, suffixed ``+`` when the tree has uncommitted
    changes, or ``None`` when it is not a git checkout."""
    revision = _git(source, "rev-parse", "--short", "HEAD")
    if revision is None:
        return None
    dirty = _git(source, "status", "--porcelain")
    return f"{revision}+" if dirty else revision


def _version_line() -> str:
    """tt's version, the tree it runs from, and that tree's revision when it is a
    checkout — the location and revision being the part that distinguishes builds."""
    revision = _source_revision(_SOURCE_ROOT)
    suffix = f" ({revision})" if revision is not None else ""
    return f"tt {package_version('tt')}{suffix} — {_SOURCE_ROOT}"


def _version_callback(show: bool) -> None:
    """``--version`` is eager: it prints and exits before the callback bootstraps a
    database or opens the TUI, so it works with no database reachable."""
    if show:
        typer.echo(_version_line())
        raise typer.Exit()


# --- the command tree -----------------------------------------------------

app = typer.Typer(
    help="A small task tracker: a command line and a terminal UI.",
    add_completion=False,
)


@app.callback(invoke_without_command=True)
def _main(
    ctx: typer.Context,
    database: Annotated[
        str | None,
        typer.Option("--db", help="The database to open. Defaults to the shared per-user file."),
    ] = None,
    # ``version`` is consumed by its eager callback, not this body.
    version: Annotated[
        bool,
        typer.Option(
            "--version",
            callback=_version_callback,
            is_eager=True,
            help="Show the version and the checkout tt runs from, then exit.",
        ),
    ] = False,
) -> None:
    """Bare ``tt`` is the terminal UI; a subcommand is the command line. So the
    callback runs even with no subcommand, and opens the TUI when none was
    invoked. Textual is imported only on that branch, so a CLI command does not
    pay to load it."""
    engine = schema.bootstrap(database)
    ctx.obj = engine
    if ctx.invoked_subcommand is None:
        from tt.frontend import tui

        tui.run(engine)


project_app = typer.Typer(help="Projects.", no_args_is_help=True)
issue_app = typer.Typer(help="Issues.", no_args_is_help=True)
epic_app = typer.Typer(help="Epics.", no_args_is_help=True)
milestone_app = typer.Typer(help="Milestones.", no_args_is_help=True)
tag_app = typer.Typer(help="Tags.", no_args_is_help=True)
comment_app = typer.Typer(help="Comments.", no_args_is_help=True)


@project_app.command("ls", help="List live projects.")
def _project_ls_command(
    ctx: typer.Context,
    as_json: Annotated[
        bool, typer.Option("--json", help="Emit a JSON array instead of the text table.")
    ] = False,
) -> None:
    _report(lambda: _project_ls(_engine(ctx), as_json))


@project_app.command("show", help="Print a project and what it offers.")
def _project_show_command(
    ctx: typer.Context,
    slug: Annotated[str, typer.Argument(help="The project's slug.")],
) -> None:
    _report(lambda: _project_show(_engine(ctx), slug))


@project_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _project_action_command(
    ctx: typer.Context,
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
    slug: Annotated[
        str | None,
        typer.Option("--slug", help="The project to run against. Omit for a top-level action."),
    ] = None,
) -> None:
    _report(lambda: _project_write(_engine(ctx), slug, key, _blob(payload)))


@project_app.command(
    "init", help="Create a project bound to a directory, the current one by default."
)
def _project_init_command(
    ctx: typer.Context,
    slug: Annotated[str, typer.Argument(help="The short name the project is addressed by.")],
    title: Annotated[str | None, typer.Option("--title", help="What to call the project.")] = None,
    body: Annotated[str | None, typer.Option("--body", help="What the project is about.")] = None,
    path: Annotated[
        str | None,
        typer.Option(
            "--path",
            help="The directory bare tt opens this project in. Defaults to the current directory.",
        ),
    ] = None,
) -> None:
    _report(lambda: _project_init(_engine(ctx), slug, title, body, path))


@issue_app.command("ls", help="List live issues.")
def _issue_ls_command(
    ctx: typer.Context,
    project: Annotated[str | None, typer.Option("--project", help="Only this project.")] = None,
    tag: Annotated[str | None, typer.Option("--tag", help="Only issues wearing this tag.")] = None,
    epic: Annotated[
        str | None,
        typer.Option("--epic", help="Only this epic's issues, by ref e.g. eng-3. Needs --project."),
    ] = None,
    milestone: Annotated[
        str | None,
        typer.Option(
            "--milestone",
            help="Only this milestone's issues, by ref e.g. eng-5. Needs --project.",
        ),
    ] = None,
    sort: Annotated[
        str | None,
        typer.Option(
            "--sort",
            help=(
                "Order as <field>[:asc|desc], field one of priority, created, updated, due, status."
            ),
        ),
    ] = None,
    as_json: Annotated[
        bool, typer.Option("--json", help="Emit a JSON array instead of the text table.")
    ] = False,
) -> None:
    _report(
        lambda: _issue_ls(_engine(ctx), project, tag, epic, milestone, _parse_sort(sort), as_json)
    )


@issue_app.command("show", help="Print an issue and what it offers.")
def _issue_show_command(
    ctx: typer.Context,
    ref: Annotated[str, typer.Argument(help="The issue's ref, e.g. ENG-12.")],
) -> None:
    _report(lambda: _issue_show(_engine(ctx), ref))


@issue_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _issue_action_command(
    ctx: typer.Context,
    ref: Annotated[str, typer.Argument(help="The issue's ref, e.g. ENG-12.")],
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _issue_write(_engine(ctx), ref, key, _blob(payload)))


@epic_app.command("ls", help="List live epics.")
def _epic_ls_command(
    ctx: typer.Context,
    project: Annotated[str | None, typer.Option("--project", help="Only this project.")] = None,
    as_json: Annotated[
        bool, typer.Option("--json", help="Emit a JSON array instead of the text table.")
    ] = False,
) -> None:
    _report(lambda: _epic_ls(_engine(ctx), project, as_json))


@epic_app.command("show", help="Print an epic and what it offers.")
def _epic_show_command(
    ctx: typer.Context,
    ref: Annotated[str, typer.Argument(help="The epic's ref, e.g. ENG-3.")],
) -> None:
    _report(lambda: _epic_show(_engine(ctx), ref))


@epic_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _epic_action_command(
    ctx: typer.Context,
    ref: Annotated[str, typer.Argument(help="The epic's ref, e.g. ENG-3.")],
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _epic_write(_engine(ctx), ref, key, _blob(payload)))


@milestone_app.command("ls", help="List live milestones.")
def _milestone_ls_command(
    ctx: typer.Context,
    epic: Annotated[
        str | None, typer.Option("--epic", help="Only this epic's milestones, by ref e.g. ENG-3.")
    ] = None,
    as_json: Annotated[
        bool, typer.Option("--json", help="Emit a JSON array instead of the text table.")
    ] = False,
) -> None:
    _report(lambda: _milestone_ls(_engine(ctx), epic, as_json))


@milestone_app.command("show", help="Print a milestone and what it offers.")
def _milestone_show_command(
    ctx: typer.Context,
    ref: Annotated[str, typer.Argument(help="The milestone's ref, e.g. ENG-5.")],
) -> None:
    _report(lambda: _milestone_show(_engine(ctx), ref))


@milestone_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _milestone_action_command(
    ctx: typer.Context,
    ref: Annotated[str, typer.Argument(help="The milestone's ref, e.g. ENG-5.")],
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _milestone_write(_engine(ctx), ref, key, _blob(payload)))


@tag_app.command("ls", help="List live tags.")
def _tag_ls_command(
    ctx: typer.Context,
    as_json: Annotated[
        bool, typer.Option("--json", help="Emit a JSON array instead of the text table.")
    ] = False,
) -> None:
    _report(lambda: _tag_ls(_engine(ctx), as_json))


@tag_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _tag_action_command(
    ctx: typer.Context,
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
    id: Annotated[
        int | None,
        typer.Option("--id", help="The tag to run against. Omit for a top-level action."),
    ] = None,
) -> None:
    _report(lambda: _tag_write(_engine(ctx), id, key, _blob(payload)))


@comment_app.command("show", help="Print a comment and what it offers.")
def _comment_show_command(
    ctx: typer.Context,
    id: Annotated[int, typer.Argument(help="The comment's id.")],
) -> None:
    _report(lambda: _comment_show(_engine(ctx), id))


@comment_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _comment_action_command(
    ctx: typer.Context,
    id: Annotated[int, typer.Argument(help="The comment's id.")],
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _comment_write(_engine(ctx), id, key, _blob(payload)))


# The generated subcommands are appended after the fixed ones, so the tree reads
# ``ls show action`` then a subcommand per action, in the order ``action_schemas``
# lists them.
_register_generated(
    project_app,
    project_api.action_schemas(),
    "slug",
    str,
    "The project's slug.",
    _project_write,
)
_register_generated(
    issue_app,
    issue_api.action_schemas(),
    "ref",
    str,
    "The issue's ref, e.g. ENG-12.",
    _issue_write,
)
_register_generated(
    epic_app,
    epic_api.action_schemas(),
    "ref",
    str,
    "The epic's ref, e.g. ENG-3.",
    _epic_write,
)
_register_generated(
    milestone_app,
    milestone_api.action_schemas(),
    "ref",
    str,
    "The milestone's ref, e.g. ENG-5.",
    _milestone_write,
)
_register_generated(
    tag_app,
    tag_api.action_schemas(),
    "id",
    int,
    "The tag's id.",
    _tag_write,
)
_register_generated(
    comment_app,
    comment_api.action_schemas(),
    "id",
    int,
    "The comment's id.",
    _comment_write,
)

app.add_typer(project_app, name="project")
app.add_typer(issue_app, name="issue")
app.add_typer(epic_app, name="epic")
app.add_typer(milestone_app, name="milestone")
app.add_typer(tag_app, name="tag")
app.add_typer(comment_app, name="comment")


def main() -> None:
    app()
