"""The domain with a shell or an agent on the end of it.

Same handful of calls the TUI makes, through the same ``api``: what an object
offers, the fields each action wants, and the write. Nothing here names an action
key — an action gets a subcommand because ``action_schemas`` lists it, and that
subcommand's options are the fields its payload derived. Adding a fifth issue
action changes no line of this file.

Two ways in, over the same ``api``. ``action KEY JSON`` is the raw path: one
command carrying any action's payload as a blob, which is what an agent holding
the output of ``show`` already has. The per-action subcommands are the same
dispatch with the blob spelled out as options, for a person at a prompt. Both end
at ``api.trigger``, so neither can reach an action the other cannot.

Typer draws the tree, but the per-action subcommands are built from
``action_schemas`` at run time: a command function is synthesised for each key,
its options the ``Field``\\ s the payload derived. A hand-written command per
action would name every key a second time and reintroduce the drift this design
exists to remove. Typer 0.27 vendors a pared-down Click that does not expose the
``Command``/``Option`` object API, so the subcommands are generated by giving each
command function a signature built at run time rather than by constructing Click
objects directly.
"""

import enum
import inspect
import json
from collections.abc import Callable
from typing import Annotated, Any, cast

import typer
from sqlalchemy import Engine

from tt import schema
from tt.domains.issue import api as issue_api
from tt.domains.issue.schemas import IssueListItem
from tt.domains.project import api as project_api
from tt.domains.project.schemas import ProjectListItem
from tt.platform import actions
from tt.platform.actions import REFUSALS, Enum, Field, Invalid, Offer, Refused, Runnable

# A refusal is the object's answer, not a usage error, so it is neither Click's 2
# nor a success. 123 is what the Rust and OCaml spikes both return for the same
# thing — distinct codes for the two refusals are a real tracker's problem and not
# this spike's.
REFUSED = 123

# The help of the two arguments the raw ``action`` path shares, factored out only
# so the command declarations stay one line each.
_KEY_HELP = "The action to run."
_JSON_HELP = "The action's arguments, as a JSON object."

# What a generated command hands its address and payload to.
type Writer = Callable[[Engine, Any, str, dict[str, Any]], str]


# --- rendering ------------------------------------------------------------


def _project_line(p: ProjectListItem) -> str:
    return f"{p.slug:<12} {p.title:<24} {p.status:<8} {p.todo} todo, {p.doing} doing, {p.done} done"


def _issue_line(i: IssueListItem) -> str:
    return f"{i.id:<4} {i.project:<12} {i.status:<8} {i.priority:<6} {i.title}"


def _field_json(field: Field) -> dict[str, Any]:
    """One argument, as the JSON an agent reads before it fills anything in."""
    base: dict[str, Any] = {
        "name": field.name,
        "required": field.required,
        "description": field.description,
    }
    match field.kind:
        case actions.Text():
            return {**base, "type": "text"}
        case actions.OptionalText():
            return {**base, "type": "text", "optional": True}
        case Enum(values=values):
            return {**base, "type": "enum", "values": values}


def _offer_json(offer: Offer) -> dict[str, Any]:
    """One offered action, as the JSON an agent reads before it picks anything."""
    fields: dict[str, Any] = {"key": offer.key, "label": offer.label}
    match offer.state:
        case Runnable():
            fields["state"] = "runnable"
        case Refused(reason):
            fields["state"] = "refused"
            fields["reason"] = reason
    fields["arguments"] = [_field_json(field) for field in offer.fields]
    return fields


def _pretty(value: Any) -> str:
    return json.dumps(value, indent=2)


# --- the writes -----------------------------------------------------------
#
# The ``api`` opens the transaction, so one call is one write with no ``with``
# here: the hooks are checked against the row as it is now rather than as some
# earlier detail view reported it, and a refusal after rows are written rolls the
# whole call back. A project write carries an optional slug — an object action
# passes one, the top-level ``createProject`` passes ``None``.


def _project_write(engine: Engine, slug: Any, key: str, payload: dict[str, Any]) -> str:
    return project_api.project_action(engine, key, payload, slug).message


def _issue_write(engine: Engine, issue_id: Any, key: str, payload: dict[str, Any]) -> str:
    return issue_api.issue_action(engine, key, payload, issue_id).message


# --- the reads ------------------------------------------------------------


def _project_ls(engine: Engine) -> str:
    return "\n".join(_project_line(p) for p in project_api.project_list(engine))


def _issue_ls(engine: Engine, project_slug: str | None) -> str:
    if project_slug is not None:
        if project_api.project_get(engine, project_slug) is None:
            raise Invalid(f"no project {project_slug!r}")
        slugs = [project_slug]
    else:
        slugs = [p.slug for p in project_api.project_list(engine)]
    lines = [_issue_line(issue) for slug in slugs for issue in issue_api.issue_list(engine, slug)]
    return "\n".join(lines)


def _project_show(engine: Engine, slug: str) -> str:
    detail, offers = project_api.project_detail(engine, slug)
    actions = [_offer_json(offer) for offer in offers]
    return _pretty({"project": detail.model_dump(mode="json"), "actions": actions})


def _issue_show(engine: Engine, issue_id: int) -> str:
    detail, offers = issue_api.issue_detail(engine, issue_id)
    actions = [_offer_json(offer) for offer in offers]
    return _pretty({"issue": detail.model_dump(mode="json"), "actions": actions})


# --- the arguments a typed-in command carries -----------------------------


def _blob(raw: str) -> dict[str, Any]:
    try:
        value: Any = json.loads(raw)
    except json.JSONDecodeError as e:
        raise Invalid(str(e)) from e
    if not isinstance(value, dict):
        raise Invalid("the payload must be a JSON object")
    return value


def _as_str(value: Any) -> str:
    """The string a field's option value carries into ``action.payload``. An enum
    option arrives as its member, whose ``.value`` is the wire string the field
    advertised; everything else is already the text that was typed."""
    if isinstance(value, enum.Enum):
        return str(value.value)
    return str(value)


def _payload_of(fields: list[Field], values: dict[str, Any]) -> dict[str, Any]:
    """What the typed-in options make.

    An option that was not passed is dropped rather than sent, which is what lets
    ``--note`` absent and ``--note ""`` mean different things: the first omits the
    field, the second sends the ``null`` ``action.payload`` encodes a blank
    optional as. Only an optional field can be absent — a required one is the
    parser's to demand — so a ``None`` against an optional field is the "not
    passed" signal.
    """
    given = [
        (field, _as_str(values[field.name]))
        for field in fields
        if field.required or values.get(field.name) is not None
    ]
    return actions.payload(given)


# --- the generated subcommands --------------------------------------------


def _enum_type(name: str, values: list[str]) -> type[enum.Enum]:
    """A closed Click choice, as the ``enum.Enum`` Typer turns into one. Its
    members' values are the wire strings, which is what Typer shows and accepts."""
    # The functional ``Enum`` call is typed as returning a member, not the class it
    # actually builds, so the cast restores what Typer needs as an annotation.
    return cast("type[enum.Enum]", enum.Enum(name, {value: value for value in values}, type=str))


def _option_annotation(field: Field) -> Any:
    """One ``--<field>`` option, its type the field's kind and its help the field's
    description. A ``Kind.Enum`` becomes a closed choice, so a bad value is a usage
    error listing the alternatives rather than a decode failure quoting a type.

    The requirement is not restated here beyond ``required=`` — what a title has to
    *contain* is the action's, which is why a blank one gets past this and is
    refused by ``execute``."""
    kind = field.kind
    base: Any = _enum_type(field.name, kind.values) if isinstance(kind, Enum) else str
    option = typer.Option(f"--{field.name}", help=field.description or "")
    if field.required:
        return Annotated[base, option]
    return Annotated[base | None, option]


def _generated(
    key: str,
    fields: list[Field],
    address_name: str,
    address_type: type,
    address_help: str,
    write: Writer,
) -> Callable[..., None]:
    """One command function per action, whether or not it applies now.

    Availability belongs to an object and a command tree does not have one yet — the
    subcommand is parsed before the row has been read. So ``delete`` is a command on
    an active project too, and the refusal comes back from the dispatch against the
    live object rather than from the parser.
    """
    address_annotation = Annotated[address_type, typer.Argument(help=address_help)]

    def impl(**kwargs: Any) -> None:
        def outcome() -> str:
            payload = _payload_of(fields, kwargs)
            engine = _engine(kwargs["ctx"])
            return write(engine, kwargs[address_name], key, payload)

        _report(outcome)

    parameters = [
        inspect.Parameter("ctx", inspect.Parameter.POSITIONAL_OR_KEYWORD, annotation=typer.Context),
        inspect.Parameter(
            address_name,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
            annotation=address_annotation,
        ),
    ]
    annotations: dict[str, Any] = {"ctx": typer.Context, address_name: address_annotation}
    for field in fields:
        annotation = _option_annotation(field)
        parameters.append(
            inspect.Parameter(
                field.name,
                inspect.Parameter.KEYWORD_ONLY,
                annotation=annotation,
                default=inspect.Parameter.empty if field.required else None,
            )
        )
        annotations[field.name] = annotation

    impl.__signature__ = inspect.Signature(parameters)  # pyright: ignore[reportFunctionMemberAccess]
    impl.__annotations__ = annotations
    impl.__name__ = key
    return impl


def _register_generated(
    sub_app: typer.Typer,
    keys: list[tuple[str, list[Field]]],
    address_name: str,
    address_type: type,
    address_help: str,
    write: Writer,
) -> None:
    for key, fields in keys:
        command = _generated(key, fields, address_name, address_type, address_help, write)
        sub_app.command(key)(command)


# --- the runtime edge -----------------------------------------------------


def _engine(ctx: typer.Context) -> Engine:
    engine = ctx.obj
    assert isinstance(engine, Engine)
    return engine


def _report(outcome: Callable[[], str]) -> None:
    """Run one command against the open database. On success print what it made; on
    any refusal print it to stderr and exit 123."""
    try:
        message = outcome()
    except REFUSALS as error:
        typer.echo(str(error), err=True)
        raise typer.Exit(code=REFUSED) from error
    typer.echo(message)


# --- the command tree -----------------------------------------------------

app = typer.Typer(
    help="A small task tracker: a command line, a terminal UI, and an MCP server.",
    no_args_is_help=True,
    add_completion=False,
)


@app.callback()
def _main(
    ctx: typer.Context,
    database: Annotated[
        str | None,
        typer.Option("--db", help="The database to open. Defaults to the shared per-user file."),
    ] = None,
) -> None:
    ctx.obj = schema.bootstrap(database)


project_app = typer.Typer(help="Projects.", no_args_is_help=True)
issue_app = typer.Typer(help="Issues.", no_args_is_help=True)


@project_app.command("ls", help="List live projects.")
def _project_ls_command(ctx: typer.Context) -> None:
    _report(lambda: _project_ls(_engine(ctx)))


@project_app.command("show", help="Print a project and what it offers.")
def _project_show_command(
    ctx: typer.Context,
    slug: Annotated[str, typer.Argument(help="The project's slug.")],
) -> None:
    _report(lambda: _project_show(_engine(ctx), slug))


@project_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _project_action_command(
    ctx: typer.Context,
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
    slug: Annotated[
        str | None,
        typer.Option("--slug", help="The project to run against. Omit for a top-level action."),
    ] = None,
) -> None:
    _report(lambda: _project_write(_engine(ctx), slug, key, _blob(payload)))


@issue_app.command("ls", help="List live issues.")
def _issue_ls_command(
    ctx: typer.Context,
    project: Annotated[str | None, typer.Option("--project", help="Only this project.")] = None,
) -> None:
    _report(lambda: _issue_ls(_engine(ctx), project))


@issue_app.command("show", help="Print an issue and what it offers.")
def _issue_show_command(
    ctx: typer.Context,
    id: Annotated[int, typer.Argument(help="The issue's id.")],
) -> None:
    _report(lambda: _issue_show(_engine(ctx), id))


@issue_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _issue_action_command(
    ctx: typer.Context,
    id: Annotated[int, typer.Argument(help="The issue's id.")],
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _issue_write(_engine(ctx), id, key, _blob(payload)))


# The generated subcommands are appended after the fixed ones, so the tree reads
# ``ls show action`` then a subcommand per action, in the order ``action_schemas``
# lists them.
_register_generated(
    project_app,
    project_api.action_schemas(),
    "slug",
    str,
    "The project's slug.",
    _project_write,
)
_register_generated(
    issue_app,
    issue_api.action_schemas(),
    "id",
    int,
    "The issue's id.",
    _issue_write,
)

app.add_typer(project_app, name="project")
app.add_typer(issue_app, name="issue")


# The other two frontends are the same tracker with a different surface, so they
# are subcommands of the one binary rather than separate entry points. Textual and
# the MCP SDK are imported only when their command runs, so ``tt issue ls`` does
# not pay to load them.
@app.command("tui", help="Open the terminal UI.")
def _tui_command(ctx: typer.Context) -> None:
    from tt.frontend import tui

    tui.run(_engine(ctx))


@app.command("mcp", help="Serve the tracker's actions as MCP tools over stdio.")
def _mcp_command(ctx: typer.Context) -> None:
    from tt.frontend import mcp

    mcp.serve(_engine(ctx))


def main() -> None:
    app()
