// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Plabrum/tt/ent/comment"
	"github.com/Plabrum/tt/ent/issue"
	"github.com/Plabrum/tt/ent/label"
	"github.com/Plabrum/tt/ent/milestone"
	"github.com/Plabrum/tt/ent/predicate"
	"github.com/Plabrum/tt/ent/project"
	"github.com/Plabrum/tt/ent/ref"
)

// IssueUpdate is the builder for updating Issue entities.
type IssueUpdate struct {
	config
	hooks    []Hook
	mutation *IssueMutation
}

// Where appends a list predicates to the IssueUpdate builder.
func (_u *IssueUpdate) Where(ps ...predicate.Issue) *IssueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IssueUpdate) SetUpdatedAt(v time.Time) *IssueUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *IssueUpdate) SetTitle(v string) *IssueUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableTitle(v *string) *IssueUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *IssueUpdate) SetBody(v string) *IssueUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableBody(v *string) *IssueUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IssueUpdate) SetStatus(v issue.Status) *IssueUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableStatus(v *issue.Status) *IssueUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *IssueUpdate) SetPriority(v issue.Priority) *IssueUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *IssueUpdate) SetNillablePriority(v *issue.Priority) *IssueUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *IssueUpdate) SetClosedAt(v time.Time) *IssueUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *IssueUpdate) SetNillableClosedAt(v *time.Time) *IssueUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *IssueUpdate) ClearClosedAt() *IssueUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *IssueUpdate) SetProjectID(id int) *IssueUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *IssueUpdate) SetProject(v *Project) *IssueUpdate {
	return _u.SetProjectID(v.ID)
}

// SetMilestoneID sets the "milestone" edge to the Milestone entity by ID.
func (_u *IssueUpdate) SetMilestoneID(id int) *IssueUpdate {
	_u.mutation.SetMilestoneID(id)
	return _u
}

// SetNillableMilestoneID sets the "milestone" edge to the Milestone entity by ID if the given value is not nil.
func (_u *IssueUpdate) SetNillableMilestoneID(id *int) *IssueUpdate {
	if id != nil {
		_u = _u.SetMilestoneID(*id)
	}
	return _u
}

// SetMilestone sets the "milestone" edge to the Milestone entity.
func (_u *IssueUpdate) SetMilestone(v *Milestone) *IssueUpdate {
	return _u.SetMilestoneID(v.ID)
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_u *IssueUpdate) AddLabelIDs(ids ...int) *IssueUpdate {
	_u.mutation.AddLabelIDs(ids...)
	return _u
}

// AddLabels adds the "labels" edges to the Label entity.
func (_u *IssueUpdate) AddLabels(v ...*Label) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *IssueUpdate) AddCommentIDs(ids ...int) *IssueUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *IssueUpdate) AddComments(v ...*Comment) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddBlockIDs adds the "blocks" edge to the Issue entity by IDs.
func (_u *IssueUpdate) AddBlockIDs(ids ...int) *IssueUpdate {
	_u.mutation.AddBlockIDs(ids...)
	return _u
}

// AddBlocks adds the "blocks" edges to the Issue entity.
func (_u *IssueUpdate) AddBlocks(v ...*Issue) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockIDs(ids...)
}

// AddBlockedByIDs adds the "blocked_by" edge to the Issue entity by IDs.
func (_u *IssueUpdate) AddBlockedByIDs(ids ...int) *IssueUpdate {
	_u.mutation.AddBlockedByIDs(ids...)
	return _u
}

// AddBlockedBy adds the "blocked_by" edges to the Issue entity.
func (_u *IssueUpdate) AddBlockedBy(v ...*Issue) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockedByIDs(ids...)
}

// AddBlockerRefIDs adds the "blocker_refs" edge to the Ref entity by IDs.
func (_u *IssueUpdate) AddBlockerRefIDs(ids ...int) *IssueUpdate {
	_u.mutation.AddBlockerRefIDs(ids...)
	return _u
}

// AddBlockerRefs adds the "blocker_refs" edges to the Ref entity.
func (_u *IssueUpdate) AddBlockerRefs(v ...*Ref) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockerRefIDs(ids...)
}

// AddBlockedRefIDs adds the "blocked_refs" edge to the Ref entity by IDs.
func (_u *IssueUpdate) AddBlockedRefIDs(ids ...int) *IssueUpdate {
	_u.mutation.AddBlockedRefIDs(ids...)
	return _u
}

// AddBlockedRefs adds the "blocked_refs" edges to the Ref entity.
func (_u *IssueUpdate) AddBlockedRefs(v ...*Ref) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockedRefIDs(ids...)
}

// Mutation returns the IssueMutation object of the builder.
func (_u *IssueUpdate) Mutation() *IssueMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *IssueUpdate) ClearProject() *IssueUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearMilestone clears the "milestone" edge to the Milestone entity.
func (_u *IssueUpdate) ClearMilestone() *IssueUpdate {
	_u.mutation.ClearMilestone()
	return _u
}

// ClearLabels clears all "labels" edges to the Label entity.
func (_u *IssueUpdate) ClearLabels() *IssueUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// RemoveLabelIDs removes the "labels" edge to Label entities by IDs.
func (_u *IssueUpdate) RemoveLabelIDs(ids ...int) *IssueUpdate {
	_u.mutation.RemoveLabelIDs(ids...)
	return _u
}

// RemoveLabels removes "labels" edges to Label entities.
func (_u *IssueUpdate) RemoveLabels(v ...*Label) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *IssueUpdate) ClearComments() *IssueUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *IssueUpdate) RemoveCommentIDs(ids ...int) *IssueUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *IssueUpdate) RemoveComments(v ...*Comment) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearBlocks clears all "blocks" edges to the Issue entity.
func (_u *IssueUpdate) ClearBlocks() *IssueUpdate {
	_u.mutation.ClearBlocks()
	return _u
}

// RemoveBlockIDs removes the "blocks" edge to Issue entities by IDs.
func (_u *IssueUpdate) RemoveBlockIDs(ids ...int) *IssueUpdate {
	_u.mutation.RemoveBlockIDs(ids...)
	return _u
}

// RemoveBlocks removes "blocks" edges to Issue entities.
func (_u *IssueUpdate) RemoveBlocks(v ...*Issue) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockIDs(ids...)
}

// ClearBlockedBy clears all "blocked_by" edges to the Issue entity.
func (_u *IssueUpdate) ClearBlockedBy() *IssueUpdate {
	_u.mutation.ClearBlockedBy()
	return _u
}

// RemoveBlockedByIDs removes the "blocked_by" edge to Issue entities by IDs.
func (_u *IssueUpdate) RemoveBlockedByIDs(ids ...int) *IssueUpdate {
	_u.mutation.RemoveBlockedByIDs(ids...)
	return _u
}

// RemoveBlockedBy removes "blocked_by" edges to Issue entities.
func (_u *IssueUpdate) RemoveBlockedBy(v ...*Issue) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockedByIDs(ids...)
}

// ClearBlockerRefs clears all "blocker_refs" edges to the Ref entity.
func (_u *IssueUpdate) ClearBlockerRefs() *IssueUpdate {
	_u.mutation.ClearBlockerRefs()
	return _u
}

// RemoveBlockerRefIDs removes the "blocker_refs" edge to Ref entities by IDs.
func (_u *IssueUpdate) RemoveBlockerRefIDs(ids ...int) *IssueUpdate {
	_u.mutation.RemoveBlockerRefIDs(ids...)
	return _u
}

// RemoveBlockerRefs removes "blocker_refs" edges to Ref entities.
func (_u *IssueUpdate) RemoveBlockerRefs(v ...*Ref) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockerRefIDs(ids...)
}

// ClearBlockedRefs clears all "blocked_refs" edges to the Ref entity.
func (_u *IssueUpdate) ClearBlockedRefs() *IssueUpdate {
	_u.mutation.ClearBlockedRefs()
	return _u
}

// RemoveBlockedRefIDs removes the "blocked_refs" edge to Ref entities by IDs.
func (_u *IssueUpdate) RemoveBlockedRefIDs(ids ...int) *IssueUpdate {
	_u.mutation.RemoveBlockedRefIDs(ids...)
	return _u
}

// RemoveBlockedRefs removes "blocked_refs" edges to Ref entities.
func (_u *IssueUpdate) RemoveBlockedRefs(v ...*Ref) *IssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockedRefIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IssueUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IssueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IssueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IssueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IssueUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := issue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IssueUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := issue.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Issue.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := issue.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Issue.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := issue.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Issue.priority": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Issue.project"`)
	}
	return nil
}

func (_u *IssueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(issue.Table, issue.Columns, sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(issue.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(issue.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(issue.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(issue.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(issue.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(issue.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(issue.FieldClosedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.ProjectTable,
			Columns: []string{issue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.ProjectTable,
			Columns: []string{issue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MilestoneCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.MilestoneTable,
			Columns: []string{issue.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MilestoneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.MilestoneTable,
			Columns: []string{issue.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.LabelsTable,
			Columns: issue.LabelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelsIDs(); len(nodes) > 0 && !_u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.LabelsTable,
			Columns: issue.LabelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.LabelsTable,
			Columns: issue.LabelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.CommentsTable,
			Columns: []string{issue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.CommentsTable,
			Columns: []string{issue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.CommentsTable,
			Columns: []string{issue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.BlocksTable,
			Columns: issue.BlocksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !_u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.BlocksTable,
			Columns: issue.BlocksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.BlocksTable,
			Columns: issue.BlocksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issue.BlockedByTable,
			Columns: issue.BlockedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockedByIDs(); len(nodes) > 0 && !_u.mutation.BlockedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issue.BlockedByTable,
			Columns: issue.BlockedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issue.BlockedByTable,
			Columns: issue.BlockedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockerRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockerRefsTable,
			Columns: []string{issue.BlockerRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockerRefsIDs(); len(nodes) > 0 && !_u.mutation.BlockerRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockerRefsTable,
			Columns: []string{issue.BlockerRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockerRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockerRefsTable,
			Columns: []string{issue.BlockerRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockedRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockedRefsTable,
			Columns: []string{issue.BlockedRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockedRefsIDs(); len(nodes) > 0 && !_u.mutation.BlockedRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockedRefsTable,
			Columns: []string{issue.BlockedRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockedRefsTable,
			Columns: []string{issue.BlockedRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IssueUpdateOne is the builder for updating a single Issue entity.
type IssueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IssueMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IssueUpdateOne) SetUpdatedAt(v time.Time) *IssueUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *IssueUpdateOne) SetTitle(v string) *IssueUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableTitle(v *string) *IssueUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *IssueUpdateOne) SetBody(v string) *IssueUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableBody(v *string) *IssueUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IssueUpdateOne) SetStatus(v issue.Status) *IssueUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableStatus(v *issue.Status) *IssueUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *IssueUpdateOne) SetPriority(v issue.Priority) *IssueUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillablePriority(v *issue.Priority) *IssueUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *IssueUpdateOne) SetClosedAt(v time.Time) *IssueUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableClosedAt(v *time.Time) *IssueUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *IssueUpdateOne) ClearClosedAt() *IssueUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *IssueUpdateOne) SetProjectID(id int) *IssueUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *IssueUpdateOne) SetProject(v *Project) *IssueUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetMilestoneID sets the "milestone" edge to the Milestone entity by ID.
func (_u *IssueUpdateOne) SetMilestoneID(id int) *IssueUpdateOne {
	_u.mutation.SetMilestoneID(id)
	return _u
}

// SetNillableMilestoneID sets the "milestone" edge to the Milestone entity by ID if the given value is not nil.
func (_u *IssueUpdateOne) SetNillableMilestoneID(id *int) *IssueUpdateOne {
	if id != nil {
		_u = _u.SetMilestoneID(*id)
	}
	return _u
}

// SetMilestone sets the "milestone" edge to the Milestone entity.
func (_u *IssueUpdateOne) SetMilestone(v *Milestone) *IssueUpdateOne {
	return _u.SetMilestoneID(v.ID)
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_u *IssueUpdateOne) AddLabelIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.AddLabelIDs(ids...)
	return _u
}

// AddLabels adds the "labels" edges to the Label entity.
func (_u *IssueUpdateOne) AddLabels(v ...*Label) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *IssueUpdateOne) AddCommentIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *IssueUpdateOne) AddComments(v ...*Comment) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddBlockIDs adds the "blocks" edge to the Issue entity by IDs.
func (_u *IssueUpdateOne) AddBlockIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.AddBlockIDs(ids...)
	return _u
}

// AddBlocks adds the "blocks" edges to the Issue entity.
func (_u *IssueUpdateOne) AddBlocks(v ...*Issue) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockIDs(ids...)
}

// AddBlockedByIDs adds the "blocked_by" edge to the Issue entity by IDs.
func (_u *IssueUpdateOne) AddBlockedByIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.AddBlockedByIDs(ids...)
	return _u
}

// AddBlockedBy adds the "blocked_by" edges to the Issue entity.
func (_u *IssueUpdateOne) AddBlockedBy(v ...*Issue) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockedByIDs(ids...)
}

// AddBlockerRefIDs adds the "blocker_refs" edge to the Ref entity by IDs.
func (_u *IssueUpdateOne) AddBlockerRefIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.AddBlockerRefIDs(ids...)
	return _u
}

// AddBlockerRefs adds the "blocker_refs" edges to the Ref entity.
func (_u *IssueUpdateOne) AddBlockerRefs(v ...*Ref) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockerRefIDs(ids...)
}

// AddBlockedRefIDs adds the "blocked_refs" edge to the Ref entity by IDs.
func (_u *IssueUpdateOne) AddBlockedRefIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.AddBlockedRefIDs(ids...)
	return _u
}

// AddBlockedRefs adds the "blocked_refs" edges to the Ref entity.
func (_u *IssueUpdateOne) AddBlockedRefs(v ...*Ref) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockedRefIDs(ids...)
}

// Mutation returns the IssueMutation object of the builder.
func (_u *IssueUpdateOne) Mutation() *IssueMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *IssueUpdateOne) ClearProject() *IssueUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearMilestone clears the "milestone" edge to the Milestone entity.
func (_u *IssueUpdateOne) ClearMilestone() *IssueUpdateOne {
	_u.mutation.ClearMilestone()
	return _u
}

// ClearLabels clears all "labels" edges to the Label entity.
func (_u *IssueUpdateOne) ClearLabels() *IssueUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// RemoveLabelIDs removes the "labels" edge to Label entities by IDs.
func (_u *IssueUpdateOne) RemoveLabelIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.RemoveLabelIDs(ids...)
	return _u
}

// RemoveLabels removes "labels" edges to Label entities.
func (_u *IssueUpdateOne) RemoveLabels(v ...*Label) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *IssueUpdateOne) ClearComments() *IssueUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *IssueUpdateOne) RemoveCommentIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *IssueUpdateOne) RemoveComments(v ...*Comment) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearBlocks clears all "blocks" edges to the Issue entity.
func (_u *IssueUpdateOne) ClearBlocks() *IssueUpdateOne {
	_u.mutation.ClearBlocks()
	return _u
}

// RemoveBlockIDs removes the "blocks" edge to Issue entities by IDs.
func (_u *IssueUpdateOne) RemoveBlockIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.RemoveBlockIDs(ids...)
	return _u
}

// RemoveBlocks removes "blocks" edges to Issue entities.
func (_u *IssueUpdateOne) RemoveBlocks(v ...*Issue) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockIDs(ids...)
}

// ClearBlockedBy clears all "blocked_by" edges to the Issue entity.
func (_u *IssueUpdateOne) ClearBlockedBy() *IssueUpdateOne {
	_u.mutation.ClearBlockedBy()
	return _u
}

// RemoveBlockedByIDs removes the "blocked_by" edge to Issue entities by IDs.
func (_u *IssueUpdateOne) RemoveBlockedByIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.RemoveBlockedByIDs(ids...)
	return _u
}

// RemoveBlockedBy removes "blocked_by" edges to Issue entities.
func (_u *IssueUpdateOne) RemoveBlockedBy(v ...*Issue) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockedByIDs(ids...)
}

// ClearBlockerRefs clears all "blocker_refs" edges to the Ref entity.
func (_u *IssueUpdateOne) ClearBlockerRefs() *IssueUpdateOne {
	_u.mutation.ClearBlockerRefs()
	return _u
}

// RemoveBlockerRefIDs removes the "blocker_refs" edge to Ref entities by IDs.
func (_u *IssueUpdateOne) RemoveBlockerRefIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.RemoveBlockerRefIDs(ids...)
	return _u
}

// RemoveBlockerRefs removes "blocker_refs" edges to Ref entities.
func (_u *IssueUpdateOne) RemoveBlockerRefs(v ...*Ref) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockerRefIDs(ids...)
}

// ClearBlockedRefs clears all "blocked_refs" edges to the Ref entity.
func (_u *IssueUpdateOne) ClearBlockedRefs() *IssueUpdateOne {
	_u.mutation.ClearBlockedRefs()
	return _u
}

// RemoveBlockedRefIDs removes the "blocked_refs" edge to Ref entities by IDs.
func (_u *IssueUpdateOne) RemoveBlockedRefIDs(ids ...int) *IssueUpdateOne {
	_u.mutation.RemoveBlockedRefIDs(ids...)
	return _u
}

// RemoveBlockedRefs removes "blocked_refs" edges to Ref entities.
func (_u *IssueUpdateOne) RemoveBlockedRefs(v ...*Ref) *IssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockedRefIDs(ids...)
}

// Where appends a list predicates to the IssueUpdate builder.
func (_u *IssueUpdateOne) Where(ps ...predicate.Issue) *IssueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IssueUpdateOne) Select(field string, fields ...string) *IssueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Issue entity.
func (_u *IssueUpdateOne) Save(ctx context.Context) (*Issue, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IssueUpdateOne) SaveX(ctx context.Context) *Issue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IssueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IssueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IssueUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := issue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IssueUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := issue.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Issue.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := issue.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Issue.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := issue.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Issue.priority": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Issue.project"`)
	}
	return nil
}

func (_u *IssueUpdateOne) sqlSave(ctx context.Context) (_node *Issue, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(issue.Table, issue.Columns, sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Issue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issue.FieldID)
		for _, f := range fields {
			if !issue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != issue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(issue.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(issue.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(issue.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(issue.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(issue.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(issue.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(issue.FieldClosedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.ProjectTable,
			Columns: []string{issue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.ProjectTable,
			Columns: []string{issue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MilestoneCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.MilestoneTable,
			Columns: []string{issue.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MilestoneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issue.MilestoneTable,
			Columns: []string{issue.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.LabelsTable,
			Columns: issue.LabelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelsIDs(); len(nodes) > 0 && !_u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.LabelsTable,
			Columns: issue.LabelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.LabelsTable,
			Columns: issue.LabelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.CommentsTable,
			Columns: []string{issue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.CommentsTable,
			Columns: []string{issue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.CommentsTable,
			Columns: []string{issue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.BlocksTable,
			Columns: issue.BlocksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !_u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.BlocksTable,
			Columns: issue.BlocksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   issue.BlocksTable,
			Columns: issue.BlocksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issue.BlockedByTable,
			Columns: issue.BlockedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockedByIDs(); len(nodes) > 0 && !_u.mutation.BlockedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issue.BlockedByTable,
			Columns: issue.BlockedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   issue.BlockedByTable,
			Columns: issue.BlockedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RefCreate{config: _u.config, mutation: newRefMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockerRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockerRefsTable,
			Columns: []string{issue.BlockerRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockerRefsIDs(); len(nodes) > 0 && !_u.mutation.BlockerRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockerRefsTable,
			Columns: []string{issue.BlockerRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockerRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockerRefsTable,
			Columns: []string{issue.BlockerRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlockedRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockedRefsTable,
			Columns: []string{issue.BlockedRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlockedRefsIDs(); len(nodes) > 0 && !_u.mutation.BlockedRefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockedRefsTable,
			Columns: []string{issue.BlockedRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockedRefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   issue.BlockedRefsTable,
			Columns: []string{issue.BlockedRefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Issue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
