// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Plabrum/tt/ent/issue"
	"github.com/Plabrum/tt/ent/milestone"
	"github.com/Plabrum/tt/ent/project"
)

// Issue is the model entity for the Issue schema.
type Issue struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Status holds the value of the "status" field.
	Status issue.Status `json:"status,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority issue.Priority `json:"priority,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IssueQuery when eager-loading is set.
	Edges            IssueEdges `json:"edges"`
	milestone_issues *int
	project_issues   *int
	selectValues     sql.SelectValues
}

// IssueEdges holds the relations/edges for other nodes in the graph.
type IssueEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Milestone holds the value of the milestone edge.
	Milestone *Milestone `json:"milestone,omitempty"`
	// Labels holds the value of the labels edge.
	Labels []*Label `json:"labels,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// Blocks holds the value of the blocks edge.
	Blocks []*Issue `json:"blocks,omitempty"`
	// BlockedBy holds the value of the blocked_by edge.
	BlockedBy []*Issue `json:"blocked_by,omitempty"`
	// BlockerRefs holds the value of the blocker_refs edge.
	BlockerRefs []*Ref `json:"blocker_refs,omitempty"`
	// BlockedRefs holds the value of the blocked_refs edge.
	BlockedRefs []*Ref `json:"blocked_refs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IssueEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// MilestoneOrErr returns the Milestone value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IssueEdges) MilestoneOrErr() (*Milestone, error) {
	if e.Milestone != nil {
		return e.Milestone, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: milestone.Label}
	}
	return nil, &NotLoadedError{edge: "milestone"}
}

// LabelsOrErr returns the Labels value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) LabelsOrErr() ([]*Label, error) {
	if e.loadedTypes[2] {
		return e.Labels, nil
	}
	return nil, &NotLoadedError{edge: "labels"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[3] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// BlocksOrErr returns the Blocks value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) BlocksOrErr() ([]*Issue, error) {
	if e.loadedTypes[4] {
		return e.Blocks, nil
	}
	return nil, &NotLoadedError{edge: "blocks"}
}

// BlockedByOrErr returns the BlockedBy value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) BlockedByOrErr() ([]*Issue, error) {
	if e.loadedTypes[5] {
		return e.BlockedBy, nil
	}
	return nil, &NotLoadedError{edge: "blocked_by"}
}

// BlockerRefsOrErr returns the BlockerRefs value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) BlockerRefsOrErr() ([]*Ref, error) {
	if e.loadedTypes[6] {
		return e.BlockerRefs, nil
	}
	return nil, &NotLoadedError{edge: "blocker_refs"}
}

// BlockedRefsOrErr returns the BlockedRefs value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) BlockedRefsOrErr() ([]*Ref, error) {
	if e.loadedTypes[7] {
		return e.BlockedRefs, nil
	}
	return nil, &NotLoadedError{edge: "blocked_refs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Issue) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case issue.FieldID:
			values[i] = new(sql.NullInt64)
		case issue.FieldTitle, issue.FieldBody, issue.FieldStatus, issue.FieldPriority:
			values[i] = new(sql.NullString)
		case issue.FieldCreatedAt, issue.FieldUpdatedAt, issue.FieldClosedAt:
			values[i] = new(sql.NullTime)
		case issue.ForeignKeys[0]: // milestone_issues
			values[i] = new(sql.NullInt64)
		case issue.ForeignKeys[1]: // project_issues
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Issue fields.
func (_m *Issue) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case issue.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case issue.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case issue.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case issue.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case issue.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case issue.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = issue.Status(value.String)
			}
		case issue.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = issue.Priority(value.String)
			}
		case issue.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case issue.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field milestone_issues", value)
			} else if value.Valid {
				_m.milestone_issues = new(int)
				*_m.milestone_issues = int(value.Int64)
			}
		case issue.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_issues", value)
			} else if value.Valid {
				_m.project_issues = new(int)
				*_m.project_issues = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Issue.
// This includes values selected through modifiers, order, etc.
func (_m *Issue) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Issue entity.
func (_m *Issue) QueryProject() *ProjectQuery {
	return NewIssueClient(_m.config).QueryProject(_m)
}

// QueryMilestone queries the "milestone" edge of the Issue entity.
func (_m *Issue) QueryMilestone() *MilestoneQuery {
	return NewIssueClient(_m.config).QueryMilestone(_m)
}

// QueryLabels queries the "labels" edge of the Issue entity.
func (_m *Issue) QueryLabels() *LabelQuery {
	return NewIssueClient(_m.config).QueryLabels(_m)
}

// QueryComments queries the "comments" edge of the Issue entity.
func (_m *Issue) QueryComments() *CommentQuery {
	return NewIssueClient(_m.config).QueryComments(_m)
}

// QueryBlocks queries the "blocks" edge of the Issue entity.
func (_m *Issue) QueryBlocks() *IssueQuery {
	return NewIssueClient(_m.config).QueryBlocks(_m)
}

// QueryBlockedBy queries the "blocked_by" edge of the Issue entity.
func (_m *Issue) QueryBlockedBy() *IssueQuery {
	return NewIssueClient(_m.config).QueryBlockedBy(_m)
}

// QueryBlockerRefs queries the "blocker_refs" edge of the Issue entity.
func (_m *Issue) QueryBlockerRefs() *RefQuery {
	return NewIssueClient(_m.config).QueryBlockerRefs(_m)
}

// QueryBlockedRefs queries the "blocked_refs" edge of the Issue entity.
func (_m *Issue) QueryBlockedRefs() *RefQuery {
	return NewIssueClient(_m.config).QueryBlockedRefs(_m)
}

// Update returns a builder for updating this Issue.
// Note that you need to call Issue.Unwrap() before calling this method if this Issue
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Issue) Update() *IssueUpdateOne {
	return NewIssueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Issue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Issue) Unwrap() *Issue {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Issue is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Issue) String() string {
	var builder strings.Builder
	builder.WriteString("Issue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Issues is a parsable slice of Issue.
type Issues []*Issue
