// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Plabrum/tt/ent/issue"
	"github.com/Plabrum/tt/ent/ref"
)

// Ref is the model entity for the Ref schema.
type Ref struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// BlockedID holds the value of the "blocked_id" field.
	BlockedID int `json:"blocked_id,omitempty"`
	// BlockerID holds the value of the "blocker_id" field.
	BlockerID int `json:"blocker_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind ref.Kind `json:"kind,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RefQuery when eager-loading is set.
	Edges        RefEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RefEdges holds the relations/edges for other nodes in the graph.
type RefEdges struct {
	// Blocked holds the value of the blocked edge.
	Blocked *Issue `json:"blocked,omitempty"`
	// Blocker holds the value of the blocker edge.
	Blocker *Issue `json:"blocker,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BlockedOrErr returns the Blocked value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RefEdges) BlockedOrErr() (*Issue, error) {
	if e.Blocked != nil {
		return e.Blocked, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: issue.Label}
	}
	return nil, &NotLoadedError{edge: "blocked"}
}

// BlockerOrErr returns the Blocker value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RefEdges) BlockerOrErr() (*Issue, error) {
	if e.Blocker != nil {
		return e.Blocker, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: issue.Label}
	}
	return nil, &NotLoadedError{edge: "blocker"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ref) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ref.FieldID, ref.FieldBlockedID, ref.FieldBlockerID:
			values[i] = new(sql.NullInt64)
		case ref.FieldKind:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ref fields.
func (_m *Ref) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ref.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ref.FieldBlockedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field blocked_id", values[i])
			} else if value.Valid {
				_m.BlockedID = int(value.Int64)
			}
		case ref.FieldBlockerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field blocker_id", values[i])
			} else if value.Valid {
				_m.BlockerID = int(value.Int64)
			}
		case ref.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = ref.Kind(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ref.
// This includes values selected through modifiers, order, etc.
func (_m *Ref) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBlocked queries the "blocked" edge of the Ref entity.
func (_m *Ref) QueryBlocked() *IssueQuery {
	return NewRefClient(_m.config).QueryBlocked(_m)
}

// QueryBlocker queries the "blocker" edge of the Ref entity.
func (_m *Ref) QueryBlocker() *IssueQuery {
	return NewRefClient(_m.config).QueryBlocker(_m)
}

// Update returns a builder for updating this Ref.
// Note that you need to call Ref.Unwrap() before calling this method if this Ref
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ref) Update() *RefUpdateOne {
	return NewRefClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ref entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ref) Unwrap() *Ref {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ref is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ref) String() string {
	var builder strings.Builder
	builder.WriteString("Ref(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("blocked_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockedID))
	builder.WriteString(", ")
	builder.WriteString("blocker_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockerID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteByte(')')
	return builder.String()
}

// Refs is a parsable slice of Ref.
type Refs []*Ref
