// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Plabrum/tt/ent/issue"
	"github.com/Plabrum/tt/ent/ref"
)

// RefCreate is the builder for creating a Ref entity.
type RefCreate struct {
	config
	mutation *RefMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBlockedID sets the "blocked_id" field.
func (_c *RefCreate) SetBlockedID(v int) *RefCreate {
	_c.mutation.SetBlockedID(v)
	return _c
}

// SetBlockerID sets the "blocker_id" field.
func (_c *RefCreate) SetBlockerID(v int) *RefCreate {
	_c.mutation.SetBlockerID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *RefCreate) SetKind(v ref.Kind) *RefCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *RefCreate) SetNillableKind(v *ref.Kind) *RefCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetBlocked sets the "blocked" edge to the Issue entity.
func (_c *RefCreate) SetBlocked(v *Issue) *RefCreate {
	return _c.SetBlockedID(v.ID)
}

// SetBlocker sets the "blocker" edge to the Issue entity.
func (_c *RefCreate) SetBlocker(v *Issue) *RefCreate {
	return _c.SetBlockerID(v.ID)
}

// Mutation returns the RefMutation object of the builder.
func (_c *RefCreate) Mutation() *RefMutation {
	return _c.mutation
}

// Save creates the Ref in the database.
func (_c *RefCreate) Save(ctx context.Context) (*Ref, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RefCreate) SaveX(ctx context.Context) *Ref {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RefCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := ref.DefaultKind
		_c.mutation.SetKind(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RefCreate) check() error {
	if _, ok := _c.mutation.BlockedID(); !ok {
		return &ValidationError{Name: "blocked_id", err: errors.New(`ent: missing required field "Ref.blocked_id"`)}
	}
	if _, ok := _c.mutation.BlockerID(); !ok {
		return &ValidationError{Name: "blocker_id", err: errors.New(`ent: missing required field "Ref.blocker_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Ref.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := ref.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Ref.kind": %w`, err)}
		}
	}
	if len(_c.mutation.BlockedIDs()) == 0 {
		return &ValidationError{Name: "blocked", err: errors.New(`ent: missing required edge "Ref.blocked"`)}
	}
	if len(_c.mutation.BlockerIDs()) == 0 {
		return &ValidationError{Name: "blocker", err: errors.New(`ent: missing required edge "Ref.blocker"`)}
	}
	return nil
}

func (_c *RefCreate) sqlSave(ctx context.Context) (*Ref, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RefCreate) createSpec() (*Ref, *sqlgraph.CreateSpec) {
	var (
		_node = &Ref{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ref.Table, sqlgraph.NewFieldSpec(ref.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(ref.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if nodes := _c.mutation.BlockedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockedTable,
			Columns: []string{ref.BlockedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlockedID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BlockerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ref.BlockerTable,
			Columns: []string{ref.BlockerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlockerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ref.Create().
//		SetBlockedID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RefUpsert) {
//			SetBlockedID(v+v).
//		}).
//		Exec(ctx)
func (_c *RefCreate) OnConflict(opts ...sql.ConflictOption) *RefUpsertOne {
	_c.conflict = opts
	return &RefUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ref.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RefCreate) OnConflictColumns(columns ...string) *RefUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RefUpsertOne{
		create: _c,
	}
}

type (
	// RefUpsertOne is the builder for "upsert"-ing
	//  one Ref node.
	RefUpsertOne struct {
		create *RefCreate
	}

	// RefUpsert is the "OnConflict" setter.
	RefUpsert struct {
		*sql.UpdateSet
	}
)

// SetBlockedID sets the "blocked_id" field.
func (u *RefUpsert) SetBlockedID(v int) *RefUpsert {
	u.Set(ref.FieldBlockedID, v)
	return u
}

// UpdateBlockedID sets the "blocked_id" field to the value that was provided on create.
func (u *RefUpsert) UpdateBlockedID() *RefUpsert {
	u.SetExcluded(ref.FieldBlockedID)
	return u
}

// SetBlockerID sets the "blocker_id" field.
func (u *RefUpsert) SetBlockerID(v int) *RefUpsert {
	u.Set(ref.FieldBlockerID, v)
	return u
}

// UpdateBlockerID sets the "blocker_id" field to the value that was provided on create.
func (u *RefUpsert) UpdateBlockerID() *RefUpsert {
	u.SetExcluded(ref.FieldBlockerID)
	return u
}

// SetKind sets the "kind" field.
func (u *RefUpsert) SetKind(v ref.Kind) *RefUpsert {
	u.Set(ref.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *RefUpsert) UpdateKind() *RefUpsert {
	u.SetExcluded(ref.FieldKind)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Ref.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RefUpsertOne) UpdateNewValues() *RefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ref.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RefUpsertOne) Ignore() *RefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RefUpsertOne) DoNothing() *RefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RefCreate.OnConflict
// documentation for more info.
func (u *RefUpsertOne) Update(set func(*RefUpsert)) *RefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RefUpsert{UpdateSet: update})
	}))
	return u
}

// SetBlockedID sets the "blocked_id" field.
func (u *RefUpsertOne) SetBlockedID(v int) *RefUpsertOne {
	return u.Update(func(s *RefUpsert) {
		s.SetBlockedID(v)
	})
}

// UpdateBlockedID sets the "blocked_id" field to the value that was provided on create.
func (u *RefUpsertOne) UpdateBlockedID() *RefUpsertOne {
	return u.Update(func(s *RefUpsert) {
		s.UpdateBlockedID()
	})
}

// SetBlockerID sets the "blocker_id" field.
func (u *RefUpsertOne) SetBlockerID(v int) *RefUpsertOne {
	return u.Update(func(s *RefUpsert) {
		s.SetBlockerID(v)
	})
}

// UpdateBlockerID sets the "blocker_id" field to the value that was provided on create.
func (u *RefUpsertOne) UpdateBlockerID() *RefUpsertOne {
	return u.Update(func(s *RefUpsert) {
		s.UpdateBlockerID()
	})
}

// SetKind sets the "kind" field.
func (u *RefUpsertOne) SetKind(v ref.Kind) *RefUpsertOne {
	return u.Update(func(s *RefUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *RefUpsertOne) UpdateKind() *RefUpsertOne {
	return u.Update(func(s *RefUpsert) {
		s.UpdateKind()
	})
}

// Exec executes the query.
func (u *RefUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RefCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RefUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RefUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RefUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RefCreateBulk is the builder for creating many Ref entities in bulk.
type RefCreateBulk struct {
	config
	err      error
	builders []*RefCreate
	conflict []sql.ConflictOption
}

// Save creates the Ref entities in the database.
func (_c *RefCreateBulk) Save(ctx context.Context) ([]*Ref, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ref, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RefCreateBulk) SaveX(ctx context.Context) []*Ref {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ref.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RefUpsert) {
//			SetBlockedID(v+v).
//		}).
//		Exec(ctx)
func (_c *RefCreateBulk) OnConflict(opts ...sql.ConflictOption) *RefUpsertBulk {
	_c.conflict = opts
	return &RefUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ref.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RefCreateBulk) OnConflictColumns(columns ...string) *RefUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RefUpsertBulk{
		create: _c,
	}
}

// RefUpsertBulk is the builder for "upsert"-ing
// a bulk of Ref nodes.
type RefUpsertBulk struct {
	create *RefCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Ref.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RefUpsertBulk) UpdateNewValues() *RefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ref.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RefUpsertBulk) Ignore() *RefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RefUpsertBulk) DoNothing() *RefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RefCreateBulk.OnConflict
// documentation for more info.
func (u *RefUpsertBulk) Update(set func(*RefUpsert)) *RefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RefUpsert{UpdateSet: update})
	}))
	return u
}

// SetBlockedID sets the "blocked_id" field.
func (u *RefUpsertBulk) SetBlockedID(v int) *RefUpsertBulk {
	return u.Update(func(s *RefUpsert) {
		s.SetBlockedID(v)
	})
}

// UpdateBlockedID sets the "blocked_id" field to the value that was provided on create.
func (u *RefUpsertBulk) UpdateBlockedID() *RefUpsertBulk {
	return u.Update(func(s *RefUpsert) {
		s.UpdateBlockedID()
	})
}

// SetBlockerID sets the "blocker_id" field.
func (u *RefUpsertBulk) SetBlockerID(v int) *RefUpsertBulk {
	return u.Update(func(s *RefUpsert) {
		s.SetBlockerID(v)
	})
}

// UpdateBlockerID sets the "blocker_id" field to the value that was provided on create.
func (u *RefUpsertBulk) UpdateBlockerID() *RefUpsertBulk {
	return u.Update(func(s *RefUpsert) {
		s.UpdateBlockerID()
	})
}

// SetKind sets the "kind" field.
func (u *RefUpsertBulk) SetKind(v ref.Kind) *RefUpsertBulk {
	return u.Update(func(s *RefUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *RefUpsertBulk) UpdateKind() *RefUpsertBulk {
	return u.Update(func(s *RefUpsert) {
		s.UpdateKind()
	})
}

// Exec executes the query.
func (u *RefUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RefCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RefCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RefUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
