// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Plabrum/tt/ent/comment"
	"github.com/Plabrum/tt/ent/issue"
	"github.com/Plabrum/tt/ent/label"
	"github.com/Plabrum/tt/ent/milestone"
	"github.com/Plabrum/tt/ent/project"
	"github.com/Plabrum/tt/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescAt is the schema descriptor for at field.
	commentDescAt := commentFields[0].Descriptor()
	// comment.DefaultAt holds the default value on creation for the at field.
	comment.DefaultAt = commentDescAt.Default.(func() time.Time)
	// commentDescAuthor is the schema descriptor for author field.
	commentDescAuthor := commentFields[1].Descriptor()
	// comment.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	comment.AuthorValidator = commentDescAuthor.Validators[0].(func(string) error)
	// commentDescBody is the schema descriptor for body field.
	commentDescBody := commentFields[2].Descriptor()
	// comment.DefaultBody holds the default value on creation for the body field.
	comment.DefaultBody = commentDescBody.Default.(string)
	issueMixin := schema.Issue{}.Mixin()
	issueMixinFields0 := issueMixin[0].Fields()
	_ = issueMixinFields0
	issueFields := schema.Issue{}.Fields()
	_ = issueFields
	// issueDescCreatedAt is the schema descriptor for created_at field.
	issueDescCreatedAt := issueMixinFields0[0].Descriptor()
	// issue.DefaultCreatedAt holds the default value on creation for the created_at field.
	issue.DefaultCreatedAt = issueDescCreatedAt.Default.(func() time.Time)
	// issueDescUpdatedAt is the schema descriptor for updated_at field.
	issueDescUpdatedAt := issueMixinFields0[1].Descriptor()
	// issue.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	issue.DefaultUpdatedAt = issueDescUpdatedAt.Default.(func() time.Time)
	// issue.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	issue.UpdateDefaultUpdatedAt = issueDescUpdatedAt.UpdateDefault.(func() time.Time)
	// issueDescTitle is the schema descriptor for title field.
	issueDescTitle := issueFields[0].Descriptor()
	// issue.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	issue.TitleValidator = issueDescTitle.Validators[0].(func(string) error)
	// issueDescBody is the schema descriptor for body field.
	issueDescBody := issueFields[1].Descriptor()
	// issue.DefaultBody holds the default value on creation for the body field.
	issue.DefaultBody = issueDescBody.Default.(string)
	labelFields := schema.Label{}.Fields()
	_ = labelFields
	// labelDescName is the schema descriptor for name field.
	labelDescName := labelFields[0].Descriptor()
	// label.NameValidator is a validator for the "name" field. It is called by the builders before save.
	label.NameValidator = labelDescName.Validators[0].(func(string) error)
	// labelDescDescription is the schema descriptor for description field.
	labelDescDescription := labelFields[1].Descriptor()
	// label.DefaultDescription holds the default value on creation for the description field.
	label.DefaultDescription = labelDescDescription.Default.(string)
	milestoneFields := schema.Milestone{}.Fields()
	_ = milestoneFields
	// milestoneDescName is the schema descriptor for name field.
	milestoneDescName := milestoneFields[0].Descriptor()
	// milestone.NameValidator is a validator for the "name" field. It is called by the builders before save.
	milestone.NameValidator = milestoneDescName.Validators[0].(func(string) error)
	// milestoneDescDescription is the schema descriptor for description field.
	milestoneDescDescription := milestoneFields[2].Descriptor()
	// milestone.DefaultDescription holds the default value on creation for the description field.
	milestone.DefaultDescription = milestoneDescDescription.Default.(string)
	projectMixin := schema.Project{}.Mixin()
	projectMixinFields0 := projectMixin[0].Fields()
	_ = projectMixinFields0
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectMixinFields0[0].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectMixinFields0[1].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescSlug is the schema descriptor for slug field.
	projectDescSlug := projectFields[0].Descriptor()
	// project.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	project.SlugValidator = projectDescSlug.Validators[0].(func(string) error)
	// projectDescTitle is the schema descriptor for title field.
	projectDescTitle := projectFields[1].Descriptor()
	// project.DefaultTitle holds the default value on creation for the title field.
	project.DefaultTitle = projectDescTitle.Default.(string)
	// projectDescDescription is the schema descriptor for description field.
	projectDescDescription := projectFields[2].Descriptor()
	// project.DefaultDescription holds the default value on creation for the description field.
	project.DefaultDescription = projectDescDescription.Default.(string)
	refFields := schema.Ref{}.Fields()
	_ = refFields
}
