"""The erased path with a shell or an agent on the end of it.

Same three calls as the TUI would make: ``wire.available`` for what is on offer,
``form.of_schema`` for the arguments, ``wire.dispatch`` for the write. Nothing here
names an action key — an action gets a subcommand because it is registered, and
that subcommand's options are the fields its payload model derived. Adding a fifth
issue action changes no line of this file.

Two ways in, over the same groups. ``action KEY JSON`` is the erased path itself:
one command carrying any action's payload as a blob, which is what an agent holding
the output of ``show`` already has. The per-action subcommands are the same dispatch
with the blob spelled out as options, for a person at a prompt. Both end at
``wire.dispatch``, so neither can reach an action the other cannot.

What this file still states is how an address becomes an object. An action writes
for itself; it does not know that a project is found by slug and a trash row by slug
among the deleted. That pairing — a live object loaded one way, a deleted one the
other — is the two arms each of ``_project_write`` and ``_issue_write``, inside one
transaction so a refusal rolls the whole call back.

Typer draws the tree, but the per-action subcommands are built from the registry at
run time: a command function is synthesised for each ``Entry``, its options the
``Field``\\ s ``of_schema`` returned. A hand-written command per action would name
every key a second time and reintroduce the drift this design exists to remove.
Typer 0.27 vendors a pared-down Click that does not expose the ``Command``/``Option``
object API, so the subcommands are generated by giving each command function a
signature built at run time rather than by constructing Click objects directly.
"""

import enum
import inspect
import json
from collections.abc import Callable
from typing import Annotated, Any, cast

import typer
from sqlalchemy import Engine
from sqlalchemy.orm import Session

from tt import schema
from tt.domains.issue import Issue
from tt.domains.issue import actions as issue_actions
from tt.domains.issue import services as issue_services
from tt.domains.project import Project, Restorable
from tt.domains.project import actions as project_actions
from tt.domains.project import services as project_services
from tt.platform import db, form, wire
from tt.platform.action import Offered, Refused, Runnable
from tt.platform.deleted import Deleted
from tt.platform.error import Error, Invalid
from tt.platform.form import Enum as EnumField
from tt.platform.form import Field, FormError

# A refusal is the object's answer, not a usage error, so it is neither Click's 2
# nor a success. 123 is what the Rust and OCaml spikes both return for the same
# thing — distinct codes for Invalid, Conflict and Broken are a real tracker's
# problem and not this spike's.
REFUSED = 123

DEFAULT_DB = "sqlite:///tt.db"

# The help of the two arguments the raw ``action`` path shares, factored out only
# so the command declarations stay one line each.
_KEY_HELP = "The action to run."
_JSON_HELP = "The action's arguments, as a JSON object."

# A write's object, chosen by which loader an address becomes an object through.
type Addressed = Project | Restorable | Issue | Deleted[Issue] | list[Project]

# What a generated command hands its address and payload to.
type Writer = Callable[[Engine, Any, str, dict[str, Any]], str]


# --- rendering ------------------------------------------------------------


def _project_line(p: Project) -> str:
    return (
        f"{p.slug:<12} {p.title:<24} {wire.name_of(p.status):<8} "
        f"{p.todo} todo, {p.doing} doing, {p.done} done"
    )


def _issue_line(i: Issue) -> str:
    return (
        f"{i.id:<4} {i.project_slug:<12} {wire.name_of(i.status):<8} "
        f"{wire.name_of(i.priority):<6} {i.title}"
    )


def _project_json(p: Project) -> dict[str, Any]:
    """The domain types carry no serialiser — deriving one would make the wire
    format a property of the domain rather than of this edge — so the one place
    that spells their fields out is here."""
    return {
        "slug": p.slug,
        "title": p.title,
        "body": p.body,
        "status": wire.name_of(p.status),
        "todo": p.todo,
        "doing": p.doing,
        "done": p.done,
        "created_at": p.created_at.isoformat(),
        "updated_at": p.updated_at.isoformat(),
    }


def _issue_json(i: Issue) -> dict[str, Any]:
    return {
        "id": i.id,
        "project": i.project_slug,
        "title": i.title,
        "body": i.body,
        "status": wire.name_of(i.status),
        "priority": wire.name_of(i.priority),
        "status_note": i.status_note,
        "created_at": i.created_at.isoformat(),
        "updated_at": i.updated_at.isoformat(),
    }


def _offer(entry: wire.Entry[Any], offered: Offered) -> dict[str, Any]:
    """One offered action, as the JSON an agent reads before it picks anything.

    The schema is passed through exactly as it was derived. Rendering it — as a
    form, as a set of options, as an agent's tool definition — is the caller's
    business."""
    fields: dict[str, Any] = {"key": entry.key}
    match offered:
        case Runnable():
            fields["state"] = "runnable"
        case Refused(reason):
            fields["state"] = "refused"
            fields["reason"] = reason
    fields["arguments"] = entry.schema
    return fields


def _offers(group: wire.Group[Any], obj: Any) -> list[dict[str, Any]]:
    return [_offer(entry, offered) for entry, offered in wire.available(group, obj)]


def _pretty(value: Any) -> str:
    return json.dumps(value, indent=2)


# --- resolution -----------------------------------------------------------
#
# Each takes the open Session, so the same load runs against the live database for
# a read and against an open transaction for a write.


def _live_project(session: Session, slug: str) -> Project:
    project = project_services.get_project(session, slug)
    if project is None:
        raise Invalid(f"no project {slug!r}")
    return project


def _restorable_project(session: Session, slug: str) -> Restorable:
    """A trash row is loaded together with the live projects, because that is what
    ``restore``'s refusal reads."""
    deleted = next(
        (d for d in project_services.trashed_projects(session) if d.inner.slug == slug),
        None,
    )
    if deleted is None:
        raise Invalid(f"no deleted project {slug!r}")
    return Restorable(deleted=deleted, live=project_services.list_projects(session))


def _live_issue(session: Session, id: int) -> Issue:
    issue = issue_services.get_issue(session, id)
    if issue is None:
        raise Invalid(f"no issue {id}")
    return issue


def _trashed_issue(session: Session, id: int) -> Deleted[Issue]:
    deleted = next(
        (d for d in issue_services.trashed_issues(session) if d.inner.id == id),
        None,
    )
    if deleted is None:
        raise Invalid(f"no deleted issue {id}")
    return deleted


def _holds(key: str, group: wire.Group[Any]) -> bool:
    return any(entry.key == key for entry in group)


# --- the writes -----------------------------------------------------------
#
# Load then dispatch, inside one transaction — so ``Action.run`` stays the only
# path to a write, the hooks are checked against the row as it is now rather than
# as some earlier ``show`` reported it, and a refusal after rows are written rolls
# the whole call back. The store call each action ends in is the action's own; all
# that is left here is choosing which loader an address becomes an object through:
# a live row for a ``group`` key, a restorable one for a ``deleted_group`` key.


def _project_write(engine: Engine, slug: Any, key: str, payload: dict[str, Any]) -> str:
    if _holds(key, project_actions.group()):
        with db.transaction(engine) as tx:
            project = _live_project(tx, slug)
            return wire.dispatch(project_actions.group(), project, key, payload, tx)
    if _holds(key, project_actions.deleted_group()):
        with db.transaction(engine) as tx:
            restorable = _restorable_project(tx, slug)
            return wire.dispatch(project_actions.deleted_group(), restorable, key, payload, tx)
    raise Invalid(f"no action {key!r}")


def _issue_write(engine: Engine, id: Any, key: str, payload: dict[str, Any]) -> str:
    if _holds(key, issue_actions.group()):
        with db.transaction(engine) as tx:
            issue = _live_issue(tx, id)
            return wire.dispatch(issue_actions.group(), issue, key, payload, tx)
    if _holds(key, issue_actions.deleted_group()):
        with db.transaction(engine) as tx:
            deleted = _trashed_issue(tx, id)
            return wire.dispatch(issue_actions.deleted_group(), deleted, key, payload, tx)
    raise Invalid(f"no action {key!r}")


def _root_write(engine: Engine, _address: Any, key: str, payload: dict[str, Any]) -> str:
    """The root creator has no object to address, so its object is the list of live
    projects — which is exactly what its uniqueness refusal has to read."""
    with db.transaction(engine) as tx:
        projects = project_services.list_projects(tx)
        return wire.dispatch(project_actions.root(), projects, key, payload, tx)


# --- the reads ------------------------------------------------------------


def _project_ls(engine: Engine) -> str:
    with db.reading(engine) as session:
        return "\n".join(_project_line(p) for p in project_services.list_projects(session))


def _issue_ls(engine: Engine, project_slug: str | None) -> str:
    with db.reading(engine) as session:
        if project_slug is not None:
            slugs = [_live_project(session, project_slug).slug]
        else:
            slugs = [p.slug for p in project_services.list_projects(session)]
        lines = [
            _issue_line(issue)
            for slug in slugs
            for issue in issue_services.list_issues(session, slug)
        ]
    return "\n".join(lines)


def _project_show(engine: Engine, slug: str) -> str:
    with db.reading(engine) as session:
        project = _live_project(session, slug)
        actions = _offers(project_actions.group(), project)
        return _pretty({"project": _project_json(project), "actions": actions})


def _issue_show(engine: Engine, id: int) -> str:
    with db.reading(engine) as session:
        issue = _live_issue(session, id)
        actions = _offers(issue_actions.group(), issue)
        return _pretty({"issue": _issue_json(issue), "actions": actions})


def _trash(engine: Engine) -> str:
    """The trash, with what each row offers — which is ``restore`` and nothing
    else, because that is the only action registered against the deleted types."""
    with db.reading(engine) as session:
        live = project_services.list_projects(session)
        projects = [
            {
                "project": deleted.inner.slug,
                "deleted_at": deleted.deleted_at.isoformat(),
                "actions": _offers(
                    project_actions.deleted_group(),
                    Restorable(deleted=deleted, live=live),
                ),
            }
            for deleted in project_services.trashed_projects(session)
        ]
        issues = [
            {
                "issue": deleted.inner.id,
                "title": deleted.inner.title,
                "deleted_at": deleted.deleted_at.isoformat(),
                "actions": _offers(issue_actions.deleted_group(), deleted),
            }
            for deleted in issue_services.trashed_issues(session)
        ]
    return _pretty({"projects": projects, "issues": issues})


# --- the arguments a typed-in command carries -----------------------------


def _blob(raw: str) -> dict[str, Any]:
    try:
        value: Any = json.loads(raw)
    except json.JSONDecodeError as e:
        raise Invalid(str(e)) from e
    if not isinstance(value, dict):
        raise Invalid("the payload must be a JSON object")
    return value


def _as_str(value: Any) -> str:
    """The string a field's option value carries into ``form.payload``. An enum
    option arrives as its member, whose ``.value`` is the wire string the schema
    advertised; everything else is already the text that was typed."""
    if isinstance(value, enum.Enum):
        return str(value.value)
    return str(value)


def _payload_of(fields: list[Field], values: dict[str, Any]) -> dict[str, Any]:
    """What the typed-in options make.

    An option that was not passed is dropped rather than sent, which is what lets
    ``--note`` absent and ``--note ""`` mean different things: the first omits the
    field, the second sends the ``null`` ``form.payload`` encodes a blank optional
    as. Only an optional field can be absent — a required one is the parser's to
    demand — so a ``None`` against an optional field is the "not passed" signal.
    """
    given = [
        (field, _as_str(values[field.name]))
        for field in fields
        if field.required or values.get(field.name) is not None
    ]
    return form.payload(given)


# --- the generated subcommands --------------------------------------------


def _enum_type(name: str, values: list[str]) -> type[enum.Enum]:
    """A closed Click choice, as the ``enum.Enum`` Typer turns into one. Its
    members' values are the wire strings, which is what Typer shows and accepts."""
    # The functional ``Enum`` call is typed as returning a member, not the class it
    # actually builds, so the cast restores what Typer needs as an annotation.
    return cast("type[enum.Enum]", enum.Enum(name, {value: value for value in values}, type=str))


def _option_annotation(field: Field) -> Any:
    """One ``--<field>`` option, its type the field's kind and its help the field's
    description. A ``Kind.Enum`` becomes a closed choice, so a bad value is a usage
    error listing the alternatives rather than a decode failure quoting a type.

    The requirement is not restated here beyond ``required=`` — what a title has to
    *contain* is the action's, which is why a blank one gets past this and is
    refused by ``execute``."""
    kind = field.kind
    base: Any = _enum_type(field.name, kind.values) if isinstance(kind, EnumField) else str
    option = typer.Option(f"--{field.name}", help=field.description or "")
    if field.required:
        return Annotated[base, option]
    return Annotated[base | None, option]


def _generated(
    key: str,
    action_schema: dict[str, Any],
    address_name: str,
    address_type: type,
    address_help: str,
    write: Writer,
) -> Callable[..., None]:
    """One command function per registered action, whether or not it applies now.

    Availability belongs to an object and a command tree does not have one yet — the
    subcommand is parsed before the row has been read. So ``delete`` is a command on
    an active project too, and the refusal comes back from the dispatch against the
    live object rather than from the parser.

    A schema with no options to render is reported rather than approximated: the
    subcommand exists and refuses at run time, because one that dropped the field it
    could not render would be refused by the decoder for a reason nothing in
    ``--help`` mentions.
    """
    try:
        fields: list[Field] | None = form.of_schema(action_schema)
        unrenderable: str | None = None
    except FormError as e:
        fields = None
        unrenderable = str(e)

    address_annotation = Annotated[address_type, typer.Argument(help=address_help)]

    def impl(**kwargs: Any) -> None:
        def outcome() -> str:
            if fields is None:
                raise Invalid(f"{key}: {unrenderable}")
            payload = _payload_of(fields, kwargs)
            engine = _engine(kwargs["ctx"])
            return write(engine, kwargs[address_name], key, payload)

        _report(outcome)

    parameters = [
        inspect.Parameter("ctx", inspect.Parameter.POSITIONAL_OR_KEYWORD, annotation=typer.Context),
        inspect.Parameter(
            address_name,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
            annotation=address_annotation,
        ),
    ]
    annotations: dict[str, Any] = {"ctx": typer.Context, address_name: address_annotation}
    for field in fields or []:
        annotation = _option_annotation(field)
        parameters.append(
            inspect.Parameter(
                field.name,
                inspect.Parameter.KEYWORD_ONLY,
                annotation=annotation,
                default=inspect.Parameter.empty if field.required else None,
            )
        )
        annotations[field.name] = annotation

    impl.__signature__ = inspect.Signature(parameters)  # pyright: ignore[reportFunctionMemberAccess]
    impl.__annotations__ = annotations
    impl.__name__ = key
    return impl


def _register_generated(
    sub_app: typer.Typer,
    keys: list[tuple[str, dict[str, Any]]],
    address_name: str,
    address_type: type,
    address_help: str,
    write: Writer,
) -> None:
    for key, action_schema in keys:
        command = _generated(key, action_schema, address_name, address_type, address_help, write)
        sub_app.command(key)(command)


def _keys(*groups: wire.Group[Any]) -> list[tuple[str, dict[str, Any]]]:
    """Every key one kind of object answers to, with the schema it advertises.

    The groups are flattened into one list, because a subcommand is a subcommand
    whether the write behind it is an update, an insert or a soft delete."""
    return [(entry.key, entry.schema) for group in groups for entry in group]


# --- the runtime edge -----------------------------------------------------


def _engine(ctx: typer.Context) -> Engine:
    engine = ctx.obj
    assert isinstance(engine, Engine)
    return engine


def _report(outcome: Callable[[], str]) -> None:
    """Run one command against the open database. On success print what it made; on
    any refusal print it to stderr and exit 123."""
    try:
        message = outcome()
    except Error as error:
        typer.echo(str(error), err=True)
        raise typer.Exit(code=REFUSED) from error
    typer.echo(message)


def _open(database: str) -> Engine:
    schema.upgrade(database)
    return db.connect(database)


# --- the command tree -----------------------------------------------------

app = typer.Typer(
    help="A small task tracker, driven from a command line.",
    no_args_is_help=True,
    add_completion=False,
)


@app.callback()
def _main(
    ctx: typer.Context,
    database: Annotated[
        str,
        typer.Option("--db", envvar="TT_DB", help="The database to open."),
    ] = DEFAULT_DB,
) -> None:
    try:
        ctx.obj = _open(database)
    except Error as error:
        typer.echo(str(error), err=True)
        raise typer.Exit(code=REFUSED) from error


project_app = typer.Typer(help="Projects.", no_args_is_help=True)
issue_app = typer.Typer(help="Issues.", no_args_is_help=True)


@project_app.command("ls", help="List live projects.")
def _project_ls_command(ctx: typer.Context) -> None:
    _report(lambda: _project_ls(_engine(ctx)))


@project_app.command("show", help="Print a project and what it offers.")
def _project_show_command(
    ctx: typer.Context,
    slug: Annotated[str, typer.Argument(help="The project's slug.")],
) -> None:
    _report(lambda: _project_show(_engine(ctx), slug))


@project_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _project_action_command(
    ctx: typer.Context,
    slug: Annotated[str, typer.Argument(help="The project's slug.")],
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _project_write(_engine(ctx), slug, key, _blob(payload)))


@issue_app.command("ls", help="List live issues.")
def _issue_ls_command(
    ctx: typer.Context,
    project: Annotated[str | None, typer.Option("--project", help="Only this project.")] = None,
) -> None:
    _report(lambda: _issue_ls(_engine(ctx), project))


@issue_app.command("show", help="Print an issue and what it offers.")
def _issue_show_command(
    ctx: typer.Context,
    id: Annotated[int, typer.Argument(help="The issue's id.")],
) -> None:
    _report(lambda: _issue_show(_engine(ctx), id))


@issue_app.command("action", help="Run an action by key, passing its arguments as JSON.")
def _issue_action_command(
    ctx: typer.Context,
    id: Annotated[int, typer.Argument(help="The issue's id.")],
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _issue_write(_engine(ctx), id, key, _blob(payload)))


# The generated subcommands are appended after the fixed ones, so the tree reads
# ``ls show action`` then a subcommand per registered action, in registration order.
_register_generated(
    project_app,
    _keys(project_actions.group(), project_actions.deleted_group()),
    "slug",
    str,
    "The project's slug.",
    _project_write,
)
_register_generated(
    issue_app,
    _keys(issue_actions.group(), issue_actions.deleted_group()),
    "id",
    int,
    "The issue's id.",
    _issue_write,
)

app.add_typer(project_app, name="project")
app.add_typer(issue_app, name="issue")


@app.command("action", help="Run a root action by key, passing its arguments as JSON.")
def _root_action_command(
    ctx: typer.Context,
    key: Annotated[str, typer.Argument(help=_KEY_HELP)],
    payload: Annotated[str, typer.Argument(help=_JSON_HELP)] = "{}",
) -> None:
    _report(lambda: _root_write(_engine(ctx), None, key, _blob(payload)))


@app.command("trash", help="What has been deleted, and what it offers.")
def _trash_command(ctx: typer.Context) -> None:
    _report(lambda: _trash(_engine(ctx)))


def main() -> None:
    app()
