// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// Milestone is the predicate function for milestone builders.
type Milestone func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Ref is the predicate function for ref builders.
type Ref func(*sql.Selector)
